import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { parseMoneyValue } from '@/lib/money'
import { loadListValues } from '@/lib/load-list-values'
import { logActivity, logFieldChangeActivities, logRecordSnapshotActivities } from '@/lib/activity'
import { generateNextClearingDocumentNumber } from '@/lib/clearing-document-number'
import { applyOpenItems, createClearingDocument, reverseOpenItemApplication } from '@/lib/open-item-service'

const MANUAL_CLEARING_EDITABLE_STATUSES = new Set(['draft', 'pending approval', 'approved'])
const MANUAL_CLEARING_POSTABLE_STATUSES = new Set(['approved'])

async function loadClearingDocumentStatusValues() {
  const values = await loadListValues('CLEARING-DOCUMENT-STATUS')
  return values.map((value) => value.toLowerCase())
}

function normalizeStatus(value: unknown, allowedStatuses: string[], fallback: string) {
  const normalized = typeof value === 'string' ? value.toLowerCase() : fallback
  return allowedStatuses.includes(normalized) ? normalized : fallback
}

function normalizeOptionalString(value: unknown) {
  const normalized = String(value ?? '').trim()
  return normalized || null
}

function normalizeOptionalAmount(value: unknown) {
  const parsed = parseMoneyValue(value)
  return parsed > 0 ? parsed : null
}

function normalizeLines(value: unknown) {
  if (!Array.isArray(value)) return []

  return value
    .map((line) => {
      const candidate = line as Record<string, unknown>
      return {
        lineRole: String(candidate.lineRole ?? '').trim() || 'manual-settlement',
        fromOpenItemId: normalizeOptionalString(candidate.fromOpenItemId),
        toOpenItemId: normalizeOptionalString(candidate.toOpenItemId),
        transactionAmount: parseMoneyValue(candidate.transactionAmount),
        memo: normalizeOptionalString(candidate.memo),
      }
    })
    .filter((line) => line.transactionAmount > 0 && (line.fromOpenItemId || line.toOpenItemId))
}

function validateManualClearingStatus(status: string) {
  if (!MANUAL_CLEARING_EDITABLE_STATUSES.has(status)) {
    throw new Error('Manual clearing documents currently support Draft, Pending Approval, and Approved only')
  }
}

async function postManualClearingDocument(id: string) {
  return prisma.$transaction(async (tx) => {
    const record = await tx.clearingDocumentHeader.findUnique({
      where: { id },
      include: {
        lines: {
          orderBy: { lineNumber: 'asc' },
        },
      },
    })

    if (!record) throw new Error('Clearing document not found')
    if (record.autoGenerated) {
      throw new Error('Auto-generated clearing documents cannot be posted manually')
    }

    const normalizedStatus = record.status.toLowerCase()
    if (normalizedStatus === 'posted') {
      throw new Error('Clearing document is already posted')
    }
    if (normalizedStatus === 'reversed') {
      throw new Error('Reversed clearing documents cannot be posted again')
    }
    if (!MANUAL_CLEARING_POSTABLE_STATUSES.has(normalizedStatus)) {
      throw new Error('Only approved manual clearing documents can be posted')
    }
    if (record.lines.length === 0) {
      throw new Error('Add at least one clearing line before posting')
    }

    const postingDate = record.postingDate ?? record.clearingDate

    for (const line of record.lines) {
      if (!line.fromOpenItemId) {
        throw new Error(`Clearing line ${line.lineNumber} must have a From Open Item before posting`)
      }

      const result = await applyOpenItems({
        tx,
        fromOpenItemId: line.fromOpenItemId,
        toOpenItemId: line.toOpenItemId ?? null,
        applicationType: 'manual_clearing_document',
        status: 'posted',
        settlementTransactionType: 'clearing-document',
        settlementTransactionId: record.id,
        applicationDate: record.clearingDate,
        postingDate,
        accountingPeriodId: record.accountingPeriodId ?? null,
        transactionAmount: Number(line.transactionAmount),
        localAmount: line.localAmount == null ? null : Number(line.localAmount),
        functionalAmount: line.functionalAmount == null ? null : Number(line.functionalAmount),
        groupAmount: line.groupAmount == null ? null : Number(line.groupAmount),
        memo: line.memo ?? record.memo ?? `Manual clearing document ${record.clearingNumber}`,
        createdById: record.createdById ?? null,
        createClearingDocument: false,
        clearingType: record.clearingType,
        automationSource: 'manual-clearing-document-post',
      })

      await tx.clearingDocumentLine.update({
        where: { id: line.id },
        data: {
          openItemApplicationId: result.application.id,
          settlementTransactionType: 'clearing-document',
          settlementTransactionId: record.id,
        },
      })
    }

    const posted = await tx.clearingDocumentHeader.update({
      where: { id: record.id },
      data: {
        status: 'posted',
        postingDate,
        postedById: record.createdById ?? null,
      },
    })

    return posted
  })
}

async function reverseManualClearingDocument(id: string) {
  return prisma.$transaction(async (tx) => {
    const record = await tx.clearingDocumentHeader.findUnique({
      where: { id },
      include: {
        lines: {
          orderBy: { lineNumber: 'asc' },
        },
      },
    })

    if (!record) throw new Error('Clearing document not found')
    if (record.autoGenerated) {
      throw new Error('Auto-generated clearing documents cannot be reversed from this workflow yet')
    }
    if (record.status.toLowerCase() !== 'posted') {
      throw new Error('Only posted manual clearing documents can be reversed')
    }
    if (record.reversedByClearingDocumentId) {
      return {
        record,
        reversalId: record.reversedByClearingDocumentId,
        alreadyReversed: true as const,
      }
    }

    const reversalDate = new Date()
    const reversalMemo = record.memo?.trim()
      ? `Reversal of ${record.clearingNumber} - ${record.memo.trim()}`
      : `Reversal of ${record.clearingNumber}`

    const reversalLinePayload = [] as Array<{
      lineRole: string
      fromOpenItemId?: string | null
      toOpenItemId?: string | null
      sourceTransactionType?: string | null
      sourceTransactionId?: string | null
      sourceTransactionLineId?: string | null
      settlementTransactionType?: string | null
      settlementTransactionId?: string | null
      transactionAmount: number
      localAmount?: number | null
      functionalAmount?: number | null
      groupAmount?: number | null
      openItemApplicationId?: string | null
      memo?: string | null
    }>

    let reversedApplications = 0
    for (const line of record.lines) {
      if (!line.openItemApplicationId) continue

      const result = await reverseOpenItemApplication(line.openItemApplicationId, {
        tx,
        reversalDate,
        postingDate: reversalDate,
        accountingPeriodId: record.accountingPeriodId ?? null,
        memo: line.memo?.trim()
          ? `Reversal of ${record.clearingNumber} - ${line.memo.trim()}`
          : `Reversal of ${record.clearingNumber}`,
        createdById: record.createdById ?? null,
        automationSource: 'manual-clearing-document-reversal',
        createClearingDocument: false,
      })

      reversalLinePayload.push({
        lineRole: `reversal_${line.lineRole}`,
        fromOpenItemId: line.fromOpenItemId ?? null,
        toOpenItemId: line.toOpenItemId ?? null,
        sourceTransactionType: line.sourceTransactionType ?? null,
        sourceTransactionId: line.sourceTransactionId ?? null,
        sourceTransactionLineId: line.sourceTransactionLineId ?? null,
        settlementTransactionType: 'clearing-document',
        settlementTransactionId: record.id,
        transactionAmount: -Number(line.transactionAmount),
        localAmount: line.localAmount == null ? null : -Number(line.localAmount),
        functionalAmount: line.functionalAmount == null ? null : -Number(line.functionalAmount),
        groupAmount: line.groupAmount == null ? null : -Number(line.groupAmount),
        openItemApplicationId: result.application.id,
        memo: line.memo?.trim()
          ? `Reversal of ${record.clearingNumber} - ${line.memo.trim()}`
          : `Reversal of ${record.clearingNumber}`,
      })
      reversedApplications += 1
    }

    if (reversedApplications === 0) {
      throw new Error('No posted settlement applications were found on this clearing document')
    }

    const reversal = await createClearingDocument({
      tx,
      clearingType: record.clearingType,
      status: 'posted',
      subsidiaryId: record.subsidiaryId ?? null,
      transactionCurrencyId: record.transactionCurrencyId ?? null,
      localCurrencyId: record.localCurrencyId ?? null,
      functionalCurrencyId: record.functionalCurrencyId ?? null,
      groupCurrencyId: record.groupCurrencyId ?? null,
      clearingDate: reversalDate,
      postingDate: reversalDate,
      accountingPeriodId: record.accountingPeriodId ?? null,
      sourceTransactionType: record.sourceTransactionType ?? null,
      sourceTransactionId: record.sourceTransactionId ?? null,
      sourceRunId: record.sourceRunId ?? null,
      counterpartyType: record.counterpartyType ?? null,
      counterpartyId: record.counterpartyId ?? null,
      transactionAmount: -Number(record.transactionAmount),
      localAmount: record.localAmount == null ? null : -Number(record.localAmount),
      functionalAmount: record.functionalAmount == null ? null : -Number(record.functionalAmount),
      groupAmount: record.groupAmount == null ? null : -Number(record.groupAmount),
      realizedFxLocalAmount:
        record.realizedFxLocalAmount == null ? null : -Number(record.realizedFxLocalAmount),
      realizedFxFunctionalAmount:
        record.realizedFxFunctionalAmount == null ? null : -Number(record.realizedFxFunctionalAmount),
      memo: reversalMemo,
      autoGenerated: false,
      automationSource: 'manual-clearing-document-reversal',
      reversesClearingDocumentId: record.id,
      createdById: record.createdById ?? null,
      lines: reversalLinePayload,
    })

    await tx.clearingDocumentHeader.update({
      where: { id: record.id },
      data: {
        status: 'reversed',
        reversedByClearingDocumentId: reversal.id,
        reversedById: record.createdById ?? null,
      },
    })

    return {
      record,
      reversalId: reversal.id,
      alreadyReversed: false as const,
    }
  })
}

export async function GET(req: NextRequest) {
  const id = req.nextUrl.searchParams.get('id')
  if (id) {
    const row = await prisma.clearingDocumentHeader.findUnique({
      where: { id },
      include: {
        accountingPeriod: true,
        lines: true,
      },
    })
    return row ? NextResponse.json(row) : NextResponse.json({ error: 'Not found' }, { status: 404 })
  }

  const rows = await prisma.clearingDocumentHeader.findMany({
    include: {
      accountingPeriod: true,
      lines: true,
    },
    orderBy: [{ createdAt: 'desc' }],
  })
  return NextResponse.json(rows)
}

export async function POST(req: NextRequest) {
  try {
    const action = req.nextUrl.searchParams.get('action')
    const actionId = req.nextUrl.searchParams.get('id')

    if (action === 'post') {
      if (!actionId) return NextResponse.json({ error: 'id required' }, { status: 400 })
      const row = await postManualClearingDocument(actionId)
      await logActivity({
        entityType: 'clearing-document',
        entityId: row.id,
        action: 'post',
        summary: `Posted manual clearing document ${row.clearingNumber}`,
      })
      return NextResponse.json({ id: row.id })
    }

    if (action === 'reverse') {
      if (!actionId) return NextResponse.json({ error: 'id required' }, { status: 400 })
      const result = await reverseManualClearingDocument(actionId)
      await logActivity({
        entityType: 'clearing-document',
        entityId: actionId,
        action: 'reverse',
        summary: result.alreadyReversed
          ? `Clearing document ${result.record.clearingNumber} was already reversed`
          : `Reversed manual clearing document ${result.record.clearingNumber}`,
      })
      return NextResponse.json({
        id: actionId,
        reversalId: result.reversalId,
        alreadyReversed: result.alreadyReversed,
      })
    }

    const body = await req.json()
    const statusValues = await loadClearingDocumentStatusValues()
    const normalizedStatus = normalizeStatus(body.status, statusValues, 'draft')
    validateManualClearingStatus(normalizedStatus)
    const normalizedLines = normalizeLines(body.lines)

    const clearingNumber = await generateNextClearingDocumentNumber()
    const amount = normalizedLines.length > 0
      ? normalizedLines.reduce((sum, line) => sum + line.transactionAmount, 0)
      : parseMoneyValue(body.transactionAmount)
    const localAmount = normalizeOptionalAmount(body.localAmount) ?? amount
    const functionalAmount = normalizeOptionalAmount(body.functionalAmount) ?? amount
    const groupAmount = normalizeOptionalAmount(body.groupAmount) ?? amount
    const clearingDate = body.clearingDate ? new Date(body.clearingDate) : new Date()
    const postingDate = body.postingDate ? new Date(body.postingDate) : null

    const row = await prisma.clearingDocumentHeader.create({
      data: {
        clearingNumber,
        clearingType: normalizeOptionalString(body.clearingType) ?? 'manual-clearing',
        status: normalizedStatus,
        subsidiaryId: normalizeOptionalString(body.subsidiaryId),
        transactionCurrencyId: normalizeOptionalString(body.transactionCurrencyId),
        localCurrencyId: normalizeOptionalString(body.localCurrencyId),
        functionalCurrencyId: normalizeOptionalString(body.functionalCurrencyId),
        groupCurrencyId: normalizeOptionalString(body.groupCurrencyId),
        clearingDate,
        postingDate,
        accountingPeriodId: normalizeOptionalString(body.accountingPeriodId),
        sourceTransactionType: normalizeOptionalString(body.sourceTransactionType),
        sourceTransactionId: normalizeOptionalString(body.sourceTransactionId),
        counterpartyType: normalizeOptionalString(body.counterpartyType),
        counterpartyId: normalizeOptionalString(body.counterpartyId),
        transactionAmount: amount,
        localAmount,
        functionalAmount,
        groupAmount,
        memo: normalizeOptionalString(body.memo),
        autoGenerated: false,
        automationSource: 'manual-clearing',
        lines: normalizedLines.length > 0
          ? {
              create: normalizedLines.map((line, index) => ({
                lineNumber: index + 1,
                lineRole: line.lineRole,
                fromOpenItemId: line.fromOpenItemId,
                toOpenItemId: line.toOpenItemId,
                transactionAmount: line.transactionAmount,
                localAmount: line.transactionAmount,
                functionalAmount: line.transactionAmount,
                groupAmount: line.transactionAmount,
                memo: line.memo,
              })),
            }
          : undefined,
      },
    })

    await logActivity({
      entityType: 'clearing-document',
      entityId: row.id,
      action: 'create',
      summary: `Created manual clearing document ${row.clearingNumber}`,
    })
    await logRecordSnapshotActivities({
      entityType: 'clearing-document',
      entityId: row.id,
      action: 'create',
      context: 'Clearing Document Details',
      fields: [
        { fieldName: 'Business Id', value: row.clearingNumber },
        { fieldName: 'Clearing Type', value: row.clearingType },
        { fieldName: 'Status', value: row.status },
        { fieldName: 'Subsidiary', value: row.subsidiaryId },
        { fieldName: 'Transaction Currency', value: row.transactionCurrencyId },
        { fieldName: 'Local Currency', value: row.localCurrencyId },
        { fieldName: 'Functional Currency', value: row.functionalCurrencyId },
        { fieldName: 'Group Currency', value: row.groupCurrencyId },
        { fieldName: 'Clearing Date', value: row.clearingDate },
        { fieldName: 'Posting Date', value: row.postingDate },
        { fieldName: 'Accounting Period', value: row.accountingPeriodId },
        { fieldName: 'Source Transaction Type', value: row.sourceTransactionType },
        { fieldName: 'Source Transaction', value: row.sourceTransactionId },
        { fieldName: 'Counterparty Type', value: row.counterpartyType },
        { fieldName: 'Counterparty', value: row.counterpartyId },
        { fieldName: 'Transaction Amount', value: row.transactionAmount },
        { fieldName: 'Local Amount', value: row.localAmount },
        { fieldName: 'Functional Amount', value: row.functionalAmount },
        { fieldName: 'Group Amount', value: row.groupAmount },
        { fieldName: 'Memo', value: row.memo },
      ],
    })

    return NextResponse.json({ id: row.id }, { status: 201 })
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unable to create clearing document'
    return NextResponse.json({ error: message }, { status: 400 })
  }
}

export async function PUT(req: NextRequest) {
  try {
    const id = req.nextUrl.searchParams.get('id')
    if (!id) return NextResponse.json({ error: 'id required' }, { status: 400 })

    const body = await req.json()
    const before = await prisma.clearingDocumentHeader.findUnique({ where: { id } })
    if (!before) return NextResponse.json({ error: 'Clearing document not found' }, { status: 404 })
    if (before.autoGenerated || !MANUAL_CLEARING_EDITABLE_STATUSES.has(before.status.toLowerCase())) {
      return NextResponse.json({ error: 'Only manual draft, pending approval, or approved clearing documents can be edited before posting' }, { status: 400 })
    }

    const statusValues = await loadClearingDocumentStatusValues()
    const normalizedStatus = normalizeStatus(body.status, statusValues, before.status.toLowerCase())
    validateManualClearingStatus(normalizedStatus)
    const normalizedLines = body.lines !== undefined ? normalizeLines(body.lines) : null
    const nextAmount = normalizedLines && normalizedLines.length > 0
      ? normalizedLines.reduce((sum, line) => sum + line.transactionAmount, 0)
      : body.transactionAmount !== undefined
        ? parseMoneyValue(body.transactionAmount)
        : null
    const nextLocalAmount =
      body.localAmount !== undefined ? (normalizeOptionalAmount(body.localAmount) ?? 0) : undefined
    const nextFunctionalAmount =
      body.functionalAmount !== undefined ? (normalizeOptionalAmount(body.functionalAmount) ?? 0) : undefined
    const nextGroupAmount =
      body.groupAmount !== undefined ? (normalizeOptionalAmount(body.groupAmount) ?? 0) : undefined

    const row = await prisma.clearingDocumentHeader.update({
      where: { id },
      data: {
        ...(body.clearingType !== undefined ? { clearingType: normalizeOptionalString(body.clearingType) ?? before.clearingType } : {}),
        ...(body.status !== undefined ? { status: normalizedStatus } : {}),
        ...(body.subsidiaryId !== undefined ? { subsidiaryId: normalizeOptionalString(body.subsidiaryId) } : {}),
        ...(body.transactionCurrencyId !== undefined ? { transactionCurrencyId: normalizeOptionalString(body.transactionCurrencyId) } : {}),
        ...(body.localCurrencyId !== undefined ? { localCurrencyId: normalizeOptionalString(body.localCurrencyId) } : {}),
        ...(body.functionalCurrencyId !== undefined ? { functionalCurrencyId: normalizeOptionalString(body.functionalCurrencyId) } : {}),
        ...(body.groupCurrencyId !== undefined ? { groupCurrencyId: normalizeOptionalString(body.groupCurrencyId) } : {}),
        ...(body.clearingDate ? { clearingDate: new Date(body.clearingDate) } : {}),
        ...(body.postingDate !== undefined ? { postingDate: body.postingDate ? new Date(body.postingDate) : null } : {}),
        ...(body.accountingPeriodId !== undefined ? { accountingPeriodId: normalizeOptionalString(body.accountingPeriodId) } : {}),
        ...(body.sourceTransactionType !== undefined ? { sourceTransactionType: normalizeOptionalString(body.sourceTransactionType) } : {}),
        ...(body.sourceTransactionId !== undefined ? { sourceTransactionId: normalizeOptionalString(body.sourceTransactionId) } : {}),
        ...(body.counterpartyType !== undefined ? { counterpartyType: normalizeOptionalString(body.counterpartyType) } : {}),
        ...(body.counterpartyId !== undefined ? { counterpartyId: normalizeOptionalString(body.counterpartyId) } : {}),
        ...(nextAmount != null
          ? {
              transactionAmount: nextAmount,
              localAmount: nextLocalAmount ?? nextAmount,
              functionalAmount: nextFunctionalAmount ?? nextAmount,
              groupAmount: nextGroupAmount ?? nextAmount,
            }
          : {}),
        ...(nextAmount == null && nextLocalAmount !== undefined ? { localAmount: nextLocalAmount } : {}),
        ...(nextAmount == null && nextFunctionalAmount !== undefined ? { functionalAmount: nextFunctionalAmount } : {}),
        ...(nextAmount == null && nextGroupAmount !== undefined ? { groupAmount: nextGroupAmount } : {}),
        ...(body.memo !== undefined ? { memo: normalizeOptionalString(body.memo) } : {}),
        ...(normalizedLines
          ? {
              lines: {
                deleteMany: {},
                create: normalizedLines.map((line, index) => ({
                  lineNumber: index + 1,
                  lineRole: line.lineRole,
                  fromOpenItemId: line.fromOpenItemId,
                  toOpenItemId: line.toOpenItemId,
                  transactionAmount: line.transactionAmount,
                  localAmount: line.transactionAmount,
                  functionalAmount: line.transactionAmount,
                  groupAmount: line.transactionAmount,
                  memo: line.memo,
                })),
              },
            }
          : {}),
      },
    })

    await logActivity({
      entityType: 'clearing-document',
      entityId: row.id,
      action: 'update',
      summary: `Updated manual clearing document ${row.clearingNumber}`,
    })
    await logFieldChangeActivities({
      entityType: 'clearing-document',
      entityId: row.id,
      context: 'Clearing Document Details',
      changes: [
        { fieldName: 'Clearing Type', oldValue: before.clearingType, newValue: row.clearingType },
        { fieldName: 'Status', oldValue: before.status, newValue: row.status },
        { fieldName: 'Subsidiary', oldValue: before.subsidiaryId, newValue: row.subsidiaryId },
        { fieldName: 'Transaction Currency', oldValue: before.transactionCurrencyId, newValue: row.transactionCurrencyId },
        { fieldName: 'Local Currency', oldValue: before.localCurrencyId, newValue: row.localCurrencyId },
        { fieldName: 'Functional Currency', oldValue: before.functionalCurrencyId, newValue: row.functionalCurrencyId },
        { fieldName: 'Group Currency', oldValue: before.groupCurrencyId, newValue: row.groupCurrencyId },
        { fieldName: 'Clearing Date', oldValue: before.clearingDate, newValue: row.clearingDate },
        { fieldName: 'Posting Date', oldValue: before.postingDate, newValue: row.postingDate },
        { fieldName: 'Accounting Period', oldValue: before.accountingPeriodId, newValue: row.accountingPeriodId },
        { fieldName: 'Source Transaction Type', oldValue: before.sourceTransactionType, newValue: row.sourceTransactionType },
        { fieldName: 'Source Transaction', oldValue: before.sourceTransactionId, newValue: row.sourceTransactionId },
        { fieldName: 'Counterparty Type', oldValue: before.counterpartyType, newValue: row.counterpartyType },
        { fieldName: 'Counterparty', oldValue: before.counterpartyId, newValue: row.counterpartyId },
        { fieldName: 'Transaction Amount', oldValue: before.transactionAmount, newValue: row.transactionAmount },
        { fieldName: 'Local Amount', oldValue: before.localAmount, newValue: row.localAmount },
        { fieldName: 'Functional Amount', oldValue: before.functionalAmount, newValue: row.functionalAmount },
        { fieldName: 'Group Amount', oldValue: before.groupAmount, newValue: row.groupAmount },
        { fieldName: 'Memo', oldValue: before.memo, newValue: row.memo },
      ],
    })

    return NextResponse.json({ id: row.id })
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unable to update clearing document'
    return NextResponse.json({ error: message }, { status: 400 })
  }
}

export async function DELETE(req: NextRequest) {
  try {
    const id = req.nextUrl.searchParams.get('id')
    if (!id) return NextResponse.json({ error: 'id required' }, { status: 400 })

    const record = await prisma.clearingDocumentHeader.findUnique({
      where: { id },
      include: { lines: { select: { id: true } } },
    })
    if (!record) return NextResponse.json({ error: 'Clearing document not found' }, { status: 404 })
    if (record.autoGenerated || record.status.toLowerCase() !== 'draft') {
      return NextResponse.json({ error: 'Only manual draft clearing documents can be deleted' }, { status: 400 })
    }

    await prisma.clearingDocumentHeader.delete({ where: { id } })
    await logActivity({
      entityType: 'clearing-document',
      entityId: id,
      action: 'delete',
      summary: `Deleted manual clearing document ${record.clearingNumber}`,
    })
    await logRecordSnapshotActivities({
      entityType: 'clearing-document',
      entityId: id,
      action: 'delete',
      context: 'Clearing Document Details',
      fields: [
        { fieldName: 'Business Id', value: record.clearingNumber },
        { fieldName: 'Clearing Type', value: record.clearingType },
        { fieldName: 'Status', value: record.status },
        { fieldName: 'Subsidiary', value: record.subsidiaryId },
        { fieldName: 'Transaction Currency', value: record.transactionCurrencyId },
        { fieldName: 'Local Currency', value: record.localCurrencyId },
        { fieldName: 'Functional Currency', value: record.functionalCurrencyId },
        { fieldName: 'Group Currency', value: record.groupCurrencyId },
        { fieldName: 'Clearing Date', value: record.clearingDate },
        { fieldName: 'Posting Date', value: record.postingDate },
        { fieldName: 'Accounting Period', value: record.accountingPeriodId },
        { fieldName: 'Source Transaction Type', value: record.sourceTransactionType },
        { fieldName: 'Source Transaction', value: record.sourceTransactionId },
        { fieldName: 'Counterparty Type', value: record.counterpartyType },
        { fieldName: 'Counterparty', value: record.counterpartyId },
        { fieldName: 'Transaction Amount', value: record.transactionAmount },
        { fieldName: 'Local Amount', value: record.localAmount },
        { fieldName: 'Functional Amount', value: record.functionalAmount },
        { fieldName: 'Group Amount', value: record.groupAmount },
        { fieldName: 'Memo', value: record.memo },
      ],
    })

    return NextResponse.json({ ok: true })
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unable to delete clearing document'
    return NextResponse.json({ error: message }, { status: 400 })
  }
}
