import type { LinkedRecordReferenceSource } from '@/lib/linked-record-reference-catalogs'
import type { TransactionStatCardSlot } from '@/lib/transaction-page-config'
import {
  buildDefaultTransactionReferenceLayout,
  type TransactionReferenceLayout,
} from '@/lib/transaction-reference-layouts'
import {
  defaultTransactionGlImpactColumns,
  defaultTransactionGlImpactSettings,
  type TransactionGlImpactColumnCustomization,
  type TransactionGlImpactColumnKey,
  type TransactionGlImpactSettings,
} from '@/lib/transaction-gl-impact'

export type ClearingDocumentDetailFieldKey =
  | 'clearingNumber'
  | 'clearingType'
  | 'status'
  | 'subsidiary'
  | 'clearingDate'
  | 'postingDate'
  | 'accountingPeriod'
  | 'sourceTransaction'
  | 'counterparty'
  | 'sourceRunId'
  | 'transactionAmount'
  | 'transactionCurrency'
  | 'localAmount'
  | 'localCurrency'
  | 'functionalAmount'
  | 'functionalCurrency'
  | 'groupAmount'
  | 'groupCurrency'
  | 'realizedFxLocalAmount'
  | 'realizedFxFunctionalAmount'
  | 'realizedFxGroupAmount'
  | 'autoGenerated'
  | 'automationSource'
  | 'exceptionStatus'
  | 'id'
  | 'createdAt'
  | 'updatedAt'

export type ClearingDocumentDetailFieldMeta = {
  id: ClearingDocumentDetailFieldKey
  label: string
  fieldType: string
  source?: string
  description?: string
}

export type ClearingDocumentDetailFieldCustomization = {
  visible: boolean
  section: string
  order: number
  column: number
}

export type ClearingDocumentStatCardKey = 'amount' | 'date' | 'type' | 'status'

export type ClearingDocumentLineColumnKey =
  | 'lineNumber'
  | 'lineRole'
  | 'transactionAmount'
  | 'localAmount'
  | 'functionalAmount'
  | 'groupAmount'
  | 'realizedFxLocalAmount'
  | 'realizedFxFunctionalAmount'
  | 'realizedFxGroupAmount'
  | 'fromOpenItem'
  | 'toOpenItem'
  | 'application'
  | 'source'
  | 'settlement'
  | 'memo'

export type ClearingDocumentLineWidthMode = 'auto' | 'compact' | 'normal' | 'wide'
export type ClearingDocumentLineFontSize = 'xs' | 'sm'

export type ClearingDocumentLineColumnMeta = {
  id: ClearingDocumentLineColumnKey
  label: string
  description?: string
}

export type ClearingDocumentLineColumnCustomization = {
  visible: boolean
  order: number
  widthMode: ClearingDocumentLineWidthMode
}

export type ClearingDocumentLineSettings = {
  fontSize: ClearingDocumentLineFontSize
}

export type ClearingDocumentDetailCustomizationConfig = {
  formColumns: number
  sections: string[]
  sectionRows: Record<string, number>
  fields: Record<ClearingDocumentDetailFieldKey, ClearingDocumentDetailFieldCustomization>
  referenceLayouts: TransactionReferenceLayout[]
  lineSettings: ClearingDocumentLineSettings
  lineColumns: Record<ClearingDocumentLineColumnKey, ClearingDocumentLineColumnCustomization>
  glImpactSettings: TransactionGlImpactSettings
  glImpactColumns: Record<TransactionGlImpactColumnKey, TransactionGlImpactColumnCustomization>
  statCards?: Array<TransactionStatCardSlot<ClearingDocumentStatCardKey>>
}

export const CLEARING_DOCUMENT_STAT_CARDS: Array<{ id: ClearingDocumentStatCardKey; label: string }> = [
  { id: 'amount', label: 'Transaction Amount' },
  { id: 'date', label: 'Clearing Date' },
  { id: 'type', label: 'Type' },
  { id: 'status', label: 'Status' },
]

export const CLEARING_DOCUMENT_DETAIL_FIELDS: ClearingDocumentDetailFieldMeta[] = [
  { id: 'clearingNumber', label: 'Business Id', fieldType: 'text', description: 'Internal operational identifier for this clearing document.' },
  { id: 'clearingType', label: 'Clearing Type', fieldType: 'list', description: 'Settlement pattern or automation type that generated this clearing document.' },
  { id: 'status', label: 'Status', fieldType: 'list', description: 'Lifecycle state for the clearing document.' },
  { id: 'subsidiary', label: 'Subsidiary', fieldType: 'list', source: 'Subsidiaries master data', description: 'Subsidiary/legal entity context for this clearing document.' },
  { id: 'clearingDate', label: 'Clearing Date', fieldType: 'date', description: 'Business date for the clearing event.' },
  { id: 'postingDate', label: 'Posting Date', fieldType: 'date', description: 'Posting date used for accounting traceability.' },
  { id: 'accountingPeriod', label: 'Accounting Period', fieldType: 'text', source: 'Accounting periods', description: 'Accounting period associated with this clearing document.' },
  { id: 'sourceTransaction', label: 'Source Transaction', fieldType: 'text', source: 'Source transaction', description: 'Source transaction that produced this clearing event.' },
  { id: 'counterparty', label: 'Counterparty', fieldType: 'text', source: 'Entity record', description: 'Counterparty context carried on the clearing document.' },
  { id: 'sourceRunId', label: 'Source Run', fieldType: 'text', source: 'Run engine', description: 'Run or orchestration instance that generated this clearing document, when applicable.' },
  { id: 'transactionAmount', label: 'Transaction Amount', fieldType: 'currency', description: 'Primary amount cleared in transaction currency.' },
  { id: 'transactionCurrency', label: 'Transaction Currency', fieldType: 'list', source: 'Currencies master data', description: 'Currency the clearing transaction is entered or settled in.' },
  { id: 'localAmount', label: 'Local Amount', fieldType: 'currency', description: 'Amount in local/statutory currency.' },
  { id: 'localCurrency', label: 'Local Currency', fieldType: 'list', source: 'Currencies master data', description: 'Statutory/company-code currency of the entity.' },
  { id: 'functionalAmount', label: 'Functional Amount', fieldType: 'currency', description: 'Amount in functional currency.' },
  { id: 'functionalCurrency', label: 'Functional Currency', fieldType: 'list', source: 'Currencies master data', description: 'Primary economic-environment currency.' },
  { id: 'groupAmount', label: 'Group Amount', fieldType: 'currency', description: 'Amount in group/reporting currency.' },
  { id: 'groupCurrency', label: 'Group Currency', fieldType: 'list', source: 'Currencies master data', description: 'Consolidated group/reporting currency.' },
  { id: 'realizedFxLocalAmount', label: 'Realized FX Local', fieldType: 'currency', description: 'Realized foreign exchange effect in local currency, when populated.' },
  { id: 'realizedFxFunctionalAmount', label: 'Realized FX Functional', fieldType: 'currency', description: 'Realized foreign exchange effect in functional currency, when populated.' },
  { id: 'realizedFxGroupAmount', label: 'Realized FX Group', fieldType: 'currency', description: 'Realized foreign exchange effect in group/reporting currency, when populated.' },
  { id: 'autoGenerated', label: 'Auto Generated', fieldType: 'checkbox', description: 'Indicates whether the clearing document was system-generated.' },
  { id: 'automationSource', label: 'Automation Source', fieldType: 'text', description: 'Subsystem or automation path that created this clearing document.' },
  { id: 'exceptionStatus', label: 'Exception Status', fieldType: 'text', description: 'Operational exception marker for reviewable clearing outcomes.' },
  { id: 'id', label: 'DB Id', fieldType: 'text', description: 'Internal database identifier for this clearing document.' },
  { id: 'createdAt', label: 'Created', fieldType: 'date', description: 'System creation timestamp.' },
  { id: 'updatedAt', label: 'Last Modified', fieldType: 'date', description: 'System last modified timestamp.' },
]

export const CLEARING_DOCUMENT_REFERENCE_SOURCES: LinkedRecordReferenceSource[] = [
  {
    id: 'sourceTransaction',
    label: 'Source Transaction',
    linkedFieldLabel: 'Source Transaction',
    description: 'Expand the transaction context that created this clearing document.',
    defaultVisibleFieldIds: ['sourceTransactionType', 'sourceTransactionNumber', 'sourceTransactionAmount'],
    defaultColumns: 2,
    defaultRows: 2,
    fields: [
      { id: 'sourceTransactionType', label: 'Type', fieldType: 'text', source: 'Source transaction', description: 'Source transaction family.', path: ['type'] },
      { id: 'sourceTransactionNumber', label: 'Business Id', fieldType: 'text', source: 'Source transaction', description: 'Source transaction business identifier.', path: ['number'] },
      { id: 'sourceTransactionStatus', label: 'Status', fieldType: 'text', source: 'Source transaction', description: 'Status carried by the source transaction when available.', path: ['status'] },
      { id: 'sourceTransactionDate', label: 'Transaction Date', fieldType: 'date', source: 'Source transaction', description: 'Transaction date from the source document when available.', path: ['date'] },
      { id: 'sourceTransactionAmount', label: 'Amount', fieldType: 'currency', source: 'Source transaction', description: 'Transaction amount from the source document when available.', path: ['amount'] },
      { id: 'sourceTransactionReference', label: 'Reference', fieldType: 'text', source: 'Source transaction', description: 'Reference or memo from the source document when available.', path: ['reference'] },
      { id: 'sourceTransactionRunId', label: 'Source Run', fieldType: 'text', source: 'Run engine', description: 'Run or orchestration instance that generated the source transaction, when carried forward.', path: ['sourceRunId'] },
    ],
  },
  {
    id: 'counterparty',
    label: 'Counterparty',
    linkedFieldLabel: 'Counterparty',
    description: 'Expand the customer, vendor, or employee context linked to this clearing document.',
    defaultVisibleFieldIds: ['counterpartyType', 'counterpartyNumber', 'counterpartyName'],
    defaultColumns: 2,
    defaultRows: 2,
    fields: [
      { id: 'counterpartyType', label: 'Type', fieldType: 'text', source: 'Entity record', description: 'Counterparty record family.', path: ['type'] },
      { id: 'counterpartyNumber', label: 'Business Id', fieldType: 'text', source: 'Entity record', description: 'Counterparty business identifier or working number/code.', path: ['number'] },
      { id: 'counterpartyName', label: 'Name', fieldType: 'text', source: 'Entity record', description: 'Display name for the linked counterparty.', path: ['name'] },
      { id: 'counterpartyEmail', label: 'Email', fieldType: 'email', source: 'Entity record', description: 'Primary email for the linked counterparty, when available.', path: ['email'] },
      { id: 'counterpartyPhone', label: 'Phone', fieldType: 'text', source: 'Entity record', description: 'Primary phone for the linked counterparty, when available.', path: ['phone'] },
      { id: 'counterpartyStatus', label: 'Status', fieldType: 'text', source: 'Entity record', description: 'Activity status for the linked counterparty, when available.', path: ['status'] },
    ],
  },
  {
    id: 'accountingPeriod',
    label: 'Accounting Period',
    linkedFieldLabel: 'Accounting Period',
    description: 'Expand the accounting-period context used by this clearing document.',
    defaultVisibleFieldIds: ['periodName', 'periodStatus', 'periodStartDate', 'periodEndDate'],
    defaultColumns: 2,
    defaultRows: 2,
    fields: [
      { id: 'periodName', label: 'Period', fieldType: 'text', source: 'Accounting periods', description: 'Name of the accounting period.', path: ['name'] },
      { id: 'periodStatus', label: 'Status', fieldType: 'text', source: 'Accounting periods', description: 'Status of the accounting period.', path: ['status'] },
      { id: 'periodStartDate', label: 'Start Date', fieldType: 'date', source: 'Accounting periods', description: 'Start date of the accounting period.', path: ['startDate'] },
      { id: 'periodEndDate', label: 'End Date', fieldType: 'date', source: 'Accounting periods', description: 'End date of the accounting period.', path: ['endDate'] },
      { id: 'periodClosed', label: 'Closed', fieldType: 'checkbox', source: 'Accounting periods', description: 'Whether the accounting period is closed.', path: ['closed'] },
      { id: 'periodArLocked', label: 'AR Locked', fieldType: 'checkbox', source: 'Accounting periods', description: 'Whether AR is locked for the period.', path: ['arLocked'] },
      { id: 'periodApLocked', label: 'AP Locked', fieldType: 'checkbox', source: 'Accounting periods', description: 'Whether AP is locked for the period.', path: ['apLocked'] },
      { id: 'periodInventoryLocked', label: 'Inventory Locked', fieldType: 'checkbox', source: 'Accounting periods', description: 'Whether inventory is locked for the period.', path: ['inventoryLocked'] },
    ],
  },
]

export const CLEARING_DOCUMENT_LINE_COLUMNS: ClearingDocumentLineColumnMeta[] = [
  { id: 'lineNumber', label: 'Line', description: 'Sequence number for the clearing line.' },
  { id: 'lineRole', label: 'Role', description: 'Role this line plays in the clearing pattern.' },
  { id: 'transactionAmount', label: 'Amount', description: 'Transaction amount carried on the clearing line.' },
  { id: 'localAmount', label: 'Local Amount', description: 'Amount carried in local/statutory currency for the clearing line.' },
  { id: 'functionalAmount', label: 'Functional Amount', description: 'Amount carried in functional currency for the clearing line.' },
  { id: 'groupAmount', label: 'Group Amount', description: 'Amount carried in group/reporting currency for the clearing line.' },
  { id: 'realizedFxLocalAmount', label: 'Realized FX Local', description: 'Realized foreign exchange effect in local currency for the clearing line.' },
  { id: 'realizedFxFunctionalAmount', label: 'Realized FX Functional', description: 'Realized foreign exchange effect in functional currency for the clearing line.' },
  { id: 'realizedFxGroupAmount', label: 'Realized FX Group', description: 'Realized foreign exchange effect in group/reporting currency for the clearing line.' },
  { id: 'fromOpenItem', label: 'From Open Item', description: 'Source open item reduced by the clearing line.' },
  { id: 'toOpenItem', label: 'To Open Item', description: 'Destination open item touched by the clearing line.' },
  { id: 'application', label: 'Application', description: 'Open-item application created for this line when applicable.' },
  { id: 'source', label: 'Source', description: 'Source transaction context for the line.' },
  { id: 'settlement', label: 'Settlement', description: 'Settlement transaction context for the line.' },
  { id: 'memo', label: 'Memo', description: 'Memo or traceability text carried on the line.' },
]

const DEFAULT_CLEARING_DOCUMENT_LINE_WIDTHS: Record<ClearingDocumentLineColumnKey, ClearingDocumentLineWidthMode> = {
  lineNumber: 'compact',
  lineRole: 'normal',
  transactionAmount: 'normal',
  localAmount: 'normal',
  functionalAmount: 'normal',
  groupAmount: 'normal',
  realizedFxLocalAmount: 'normal',
  realizedFxFunctionalAmount: 'normal',
  realizedFxGroupAmount: 'normal',
  fromOpenItem: 'wide',
  toOpenItem: 'wide',
  application: 'wide',
  source: 'wide',
  settlement: 'wide',
  memo: 'wide',
}

export function defaultClearingDocumentDetailCustomization(): ClearingDocumentDetailCustomizationConfig {
  return {
    formColumns: 3,
    sections: [
      'Document Identity',
      'Clearing Context',
      'Source and Counterparty',
      'Amounts and Automation',
      'Record Keys and System Dates',
    ],
    sectionRows: {
      'Document Identity': 1,
      'Clearing Context': 3,
      'Source and Counterparty': 1,
      'Amounts and Automation': 2,
      'Record Keys and System Dates': 1,
    },
    fields: {
      clearingNumber: { visible: true, section: 'Document Identity', order: 0, column: 1 },
      clearingType: { visible: true, section: 'Document Identity', order: 0, column: 2 },
      status: { visible: true, section: 'Document Identity', order: 0, column: 3 },
      subsidiary: { visible: true, section: 'Clearing Context', order: 0, column: 1 },
      clearingDate: { visible: true, section: 'Clearing Context', order: 0, column: 2 },
      postingDate: { visible: true, section: 'Clearing Context', order: 0, column: 3 },
      accountingPeriod: { visible: true, section: 'Clearing Context', order: 1, column: 1 },
      transactionAmount: { visible: true, section: 'Clearing Context', order: 1, column: 2 },
      transactionCurrency: { visible: true, section: 'Clearing Context', order: 1, column: 3 },
      localAmount: { visible: true, section: 'Clearing Context', order: 2, column: 1 },
      localCurrency: { visible: true, section: 'Clearing Context', order: 2, column: 2 },
      functionalAmount: { visible: true, section: 'Clearing Context', order: 2, column: 3 },
      sourceTransaction: { visible: true, section: 'Source and Counterparty', order: 0, column: 1 },
      counterparty: { visible: true, section: 'Source and Counterparty', order: 0, column: 2 },
      sourceRunId: { visible: true, section: 'Source and Counterparty', order: 0, column: 3 },
      functionalCurrency: { visible: true, section: 'Amounts and Automation', order: 0, column: 1 },
      groupAmount: { visible: true, section: 'Amounts and Automation', order: 0, column: 2 },
      groupCurrency: { visible: true, section: 'Amounts and Automation', order: 0, column: 3 },
      realizedFxLocalAmount: { visible: true, section: 'Amounts and Automation', order: 1, column: 1 },
      realizedFxFunctionalAmount: { visible: true, section: 'Amounts and Automation', order: 1, column: 2 },
      realizedFxGroupAmount: { visible: true, section: 'Amounts and Automation', order: 1, column: 3 },
      autoGenerated: { visible: true, section: 'Amounts and Automation', order: 2, column: 1 },
      automationSource: { visible: true, section: 'Amounts and Automation', order: 2, column: 2 },
      exceptionStatus: { visible: true, section: 'Amounts and Automation', order: 2, column: 3 },
      id: { visible: true, section: 'Record Keys and System Dates', order: 0, column: 1 },
      createdAt: { visible: true, section: 'Record Keys and System Dates', order: 0, column: 2 },
      updatedAt: { visible: true, section: 'Record Keys and System Dates', order: 0, column: 3 },
    },
    referenceLayouts: [
      buildDefaultTransactionReferenceLayout(CLEARING_DOCUMENT_REFERENCE_SOURCES, 'sourceTransaction'),
      buildDefaultTransactionReferenceLayout(CLEARING_DOCUMENT_REFERENCE_SOURCES, 'counterparty', 'reference-counterparty-1'),
      buildDefaultTransactionReferenceLayout(CLEARING_DOCUMENT_REFERENCE_SOURCES, 'accountingPeriod', 'reference-accounting-period-1'),
    ],
    lineSettings: { fontSize: 'xs' },
    lineColumns: Object.fromEntries(
      CLEARING_DOCUMENT_LINE_COLUMNS.map((column, index) => [
        column.id,
        {
          visible: true,
          order: index,
          widthMode: DEFAULT_CLEARING_DOCUMENT_LINE_WIDTHS[column.id],
        },
      ]),
    ) as Record<ClearingDocumentLineColumnKey, ClearingDocumentLineColumnCustomization>,
    glImpactSettings: defaultTransactionGlImpactSettings(),
    glImpactColumns: defaultTransactionGlImpactColumns(),
    statCards: [
      { id: 'clearing-amount', metric: 'amount', visible: true, order: 0 },
      { id: 'clearing-date', metric: 'date', visible: true, order: 1 },
      { id: 'clearing-type', metric: 'type', visible: true, order: 2 },
      { id: 'clearing-status', metric: 'status', visible: true, order: 3 },
    ],
  }
}
