import { Prisma } from '@prisma/client'
import { prisma } from '@/lib/prisma'

type DbClient = typeof prisma | Prisma.TransactionClient

export type DocumentRelationshipRecordType =
  | 'bill'
  | 'bill-payment'
  | 'invoice'
  | 'invoice-receipt'
  | 'journal-entry'

export type DocumentRelationshipType = 'settles' | 'reverses'

export type DocumentRelationshipSummary = {
  id: string
  direction: 'outbound' | 'inbound'
  relationshipType: DocumentRelationshipType | string
  relationshipLabel: string
  relatedRecordType: string
  relatedRecordLabel: string
  relatedRecordId: string
  relatedNumber: string
  relatedStatus: string | null
  relatedAmount: number | null
  relatedDate: string | null
  relatedDescription: string | null
  href: string | null
}

export function humanizeDocumentRelationshipValue(value: string | null | undefined) {
  if (!value) return '-'
  return value
    .split(/[_-]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ')
}

export function buildDocumentRelationshipHref(
  type: string | null | undefined,
  id: string | null | undefined,
) {
  if (!type || !id) return null
  switch (type) {
    case 'bill':
      return `/bills/${id}`
    case 'bill-payment':
      return `/bill-payments/${id}`
    case 'invoice':
      return `/invoices/${id}`
    case 'invoice-receipt':
      return `/invoice-receipts/${id}`
    case 'journal-entry':
      return `/journals/${id}`
    default:
      return null
  }
}

export async function syncAutoDocumentRelationshipsForSource(
  input: {
    sourceRecordType: string
    sourceRecordId: string
    relationshipType: string
    automationSource: string
    targets: Array<{ recordType: string; recordId: string }>
  },
  db: DbClient = prisma,
) {
  const seen = new Set<string>()
  const targets = input.targets.filter((target) => {
    if (!target.recordType || !target.recordId) return false
    const key = `${target.recordType}:${target.recordId}`
    if (seen.has(key)) return false
    seen.add(key)
    return true
  })

  await db.documentRelationship.deleteMany({
    where: {
      sourceRecordType: input.sourceRecordType,
      sourceRecordId: input.sourceRecordId,
      relationshipType: input.relationshipType,
      autoGenerated: true,
      automationSource: input.automationSource,
    },
  })

  if (!targets.length) return

  await db.documentRelationship.createMany({
    data: targets.map((target) => ({
      sourceRecordType: input.sourceRecordType,
      sourceRecordId: input.sourceRecordId,
      targetRecordType: target.recordType,
      targetRecordId: target.recordId,
      relationshipType: input.relationshipType,
      autoGenerated: true,
      automationSource: input.automationSource,
    })),
    skipDuplicates: true,
  })
}

export async function deleteDocumentRelationshipsForRecord(
  recordType: string,
  recordId: string,
  db: DbClient = prisma,
) {
  await db.documentRelationship.deleteMany({
    where: {
      OR: [
        { sourceRecordType: recordType, sourceRecordId: recordId },
        { targetRecordType: recordType, targetRecordId: recordId },
      ],
    },
  })
}

export async function loadDocumentRelationshipSummaries(
  input: {
    recordType: string
    recordId: string
  },
  db: DbClient = prisma,
): Promise<DocumentRelationshipSummary[]> {
  const relationships = await db.documentRelationship.findMany({
    where: {
      OR: [
        { sourceRecordType: input.recordType, sourceRecordId: input.recordId },
        { targetRecordType: input.recordType, targetRecordId: input.recordId },
      ],
    },
    orderBy: [{ createdAt: 'asc' }, { targetRecordType: 'asc' }, { targetRecordId: 'asc' }],
  })

  if (!relationships.length) return []

  const idsByType = new Map<string, Set<string>>()
  for (const relationship of relationships) {
    const isOutbound =
      relationship.sourceRecordType === input.recordType
      && relationship.sourceRecordId === input.recordId
    const relatedRecordType = isOutbound
      ? relationship.targetRecordType
      : relationship.sourceRecordType
    const relatedRecordId = isOutbound
      ? relationship.targetRecordId
      : relationship.sourceRecordId
    if (!idsByType.has(relatedRecordType)) idsByType.set(relatedRecordType, new Set())
    idsByType.get(relatedRecordType)?.add(relatedRecordId)
  }

  const [bills, billPayments, invoices, invoiceReceipts, journals] = await Promise.all([
    idsByType.get('bill')?.size
      ? db.bill.findMany({
          where: { id: { in: Array.from(idsByType.get('bill') ?? []) } },
          select: { id: true, number: true, status: true, total: true, date: true, notes: true },
        })
      : Promise.resolve([]),
    idsByType.get('bill-payment')?.size
      ? db.billPayment.findMany({
          where: { id: { in: Array.from(idsByType.get('bill-payment') ?? []) } },
          select: { id: true, number: true, status: true, amount: true, date: true, notes: true },
        })
      : Promise.resolve([]),
    idsByType.get('invoice')?.size
      ? db.invoice.findMany({
          where: { id: { in: Array.from(idsByType.get('invoice') ?? []) } },
          select: { id: true, number: true, status: true, total: true, dueDate: true, createdAt: true },
        })
      : Promise.resolve([]),
    idsByType.get('invoice-receipt')?.size
      ? db.cashReceipt.findMany({
          where: { id: { in: Array.from(idsByType.get('invoice-receipt') ?? []) } },
          select: { id: true, number: true, status: true, amount: true, date: true, reference: true },
        })
      : Promise.resolve([]),
    idsByType.get('journal-entry')?.size
      ? db.journalEntry.findMany({
          where: { id: { in: Array.from(idsByType.get('journal-entry') ?? []) } },
          select: { id: true, number: true, status: true, total: true, date: true, description: true },
        })
      : Promise.resolve([]),
  ])

  const billById = new Map(
    bills.map((bill) => [
      bill.id,
      {
        relatedNumber: bill.number,
        relatedStatus: bill.status,
        relatedAmount: Number(bill.total),
        relatedDate: bill.date.toISOString(),
        relatedDescription: bill.notes ?? null,
      },
    ]),
  )
  const billPaymentById = new Map(
    billPayments.map((payment) => [
      payment.id,
      {
        relatedNumber: payment.number,
        relatedStatus: payment.status,
        relatedAmount: Number(payment.amount),
        relatedDate: payment.date.toISOString(),
        relatedDescription: payment.notes ?? null,
      },
    ]),
  )
  const invoiceById = new Map(
    invoices.map((invoice) => [
      invoice.id,
      {
        relatedNumber: invoice.number,
        relatedStatus: invoice.status,
        relatedAmount: Number(invoice.total),
        relatedDate: (invoice.dueDate ?? invoice.createdAt).toISOString(),
        relatedDescription: null,
      },
    ]),
  )
  const invoiceReceiptById = new Map(
    invoiceReceipts.map((receipt) => [
      receipt.id,
      {
        relatedNumber: receipt.number ?? receipt.id,
        relatedStatus: receipt.status,
        relatedAmount: Number(receipt.amount),
        relatedDate: receipt.date.toISOString(),
        relatedDescription: receipt.reference ?? null,
      },
    ]),
  )
  const journalById = new Map(
    journals.map((journal) => [
      journal.id,
      {
        relatedNumber: journal.number,
        relatedStatus: journal.status,
        relatedAmount: Number(journal.total),
        relatedDate: journal.date.toISOString(),
        relatedDescription: journal.description ?? null,
      },
    ]),
  )

  const summaries = relationships.map((relationship) => {
      const direction =
        relationship.sourceRecordType === input.recordType
        && relationship.sourceRecordId === input.recordId
          ? 'outbound'
          : 'inbound'
      const relatedRecordType =
        direction === 'outbound'
          ? relationship.targetRecordType
          : relationship.sourceRecordType
      const relatedRecordId =
        direction === 'outbound'
          ? relationship.targetRecordId
          : relationship.sourceRecordId

      const recordDetails =
        relatedRecordType === 'bill'
          ? billById.get(relatedRecordId)
          : relatedRecordType === 'bill-payment'
            ? billPaymentById.get(relatedRecordId)
            : relatedRecordType === 'invoice'
              ? invoiceById.get(relatedRecordId)
              : relatedRecordType === 'invoice-receipt'
                ? invoiceReceiptById.get(relatedRecordId)
                : relatedRecordType === 'journal-entry'
                  ? journalById.get(relatedRecordId)
                  : null

      if (!recordDetails) return null

      return {
        id: relationship.id,
        direction,
        relationshipType: relationship.relationshipType,
        relationshipLabel: humanizeDocumentRelationshipValue(relationship.relationshipType),
        relatedRecordType,
        relatedRecordLabel: humanizeDocumentRelationshipValue(relatedRecordType),
        relatedRecordId,
        relatedNumber: recordDetails.relatedNumber,
        relatedStatus: recordDetails.relatedStatus,
        relatedAmount: recordDetails.relatedAmount,
        relatedDate: recordDetails.relatedDate,
        relatedDescription: recordDetails.relatedDescription,
        href: buildDocumentRelationshipHref(relatedRecordType, relatedRecordId),
      } as DocumentRelationshipSummary
    })
  return summaries.filter((relationship): relationship is DocumentRelationshipSummary => relationship !== null)
}
