export type FormKey =
  | 'customerCreate'
  | 'contactCreate'
  | 'vendorCreate'
  | 'leadCreate'
  | 'opportunityCreate'
  | 'quoteCreate'
  | 'salesOrderCreate'
  | 'fulfillmentCreate'
  | 'invoiceCreate'
  | 'invoiceReceiptCreate'
  | 'creditMemoCreate'
  | 'customerRefundCreate'
  | 'vendorRefundCreate'
  | 'purchaseRequisitionCreate'
  | 'purchaseOrderCreate'
  | 'receiptCreate'
  | 'billCreate'
  | 'billCreditCreate'
  | 'billPaymentCreate'
  | 'journalCreate'
  | 'itemCreate'
  | 'currencyCreate'
  | 'accountingPeriodCreate'
  | 'locationCreate'
  | 'chartOfAccountCreate'
  | 'departmentCreate'
  | 'employeeCreate'
  | 'subsidiaryCreate'
  | 'roleCreate'
  | 'userCreate'

export type FormRequirements = Record<string, boolean>
export type FormRequirementsMap = Record<FormKey, FormRequirements>

/**
 * Centralized required-field configuration by form.
 * Toggle booleans here to change required fields per company preference.
 */
export const FORM_REQUIREMENTS: FormRequirementsMap = {
  customerCreate: {
    customerId: false,
    name: true,
    email: true,
    phone: true,
    address: true,
    industry: false,
    primarySubsidiaryId: false,
    primaryCurrencyId: false,
    inactive: false,
    primaryContact: true,
    contactFirstName: true,
    contactLastName: true,
    addressStreet1: true,
    addressCity: true,
    addressStateProvince: true,
    addressPostalCode: true,
    addressCountry: true,
  },
  contactCreate: {
    contactNumber: false,
    firstName: true,
    lastName: true,
    customerId: false,
    vendorId: false,
    email: false,
    phone: false,
    address: false,
    position: false,
    inactive: false,
  },
  vendorCreate: {
    vendorNumber: false,
    name: true,
    email: false,
    phone: false,
    address: false,
    taxId: false,
    primarySubsidiaryId: false,
    primaryCurrencyId: false,
    inactive: false,
  },
  leadCreate: {
    firstName: true,
    lastName: true,
    email: true,
    phone: false,
    company: true,
    title: false,
    website: false,
    industry: false,
    status: true,
    source: false,
    rating: false,
    expectedValue: false,
    subsidiaryId: false,
    currencyId: false,
    address: false,
    notes: false,
    lastContactedAt: false,
    qualifiedAt: false,
    convertedAt: false,
  },
  opportunityCreate: {
    name: true,
    customerId: true,
    amount: false,
    stage: true,
    closeDate: true,
    subsidiaryId: true,
    currencyId: true,
  },
  quoteCreate: {
    opportunity: true,
    customerId: false,
    number: false,
    status: true,
    validUntil: true,
    subsidiaryId: true,
    currencyId: true,
    notes: false,
  },
  salesOrderCreate: {
    customerId: true,
    userId: false,
    quoteId: false,
    number: false,
    subsidiaryId: true,
    currencyId: true,
    status: true,
    total: false,
  },
  fulfillmentCreate: {
    salesOrderId: true,
    status: true,
    date: false,
    notes: false,
    subsidiaryId: true,
    currencyId: true,
  },
  invoiceCreate: {
    salesOrderId: false,
    customerId: true,
    status: true,
    dueDate: true,
    paidDate: false,
    subsidiaryId: true,
    currencyId: true,
  },
  invoiceReceiptCreate: {
    invoiceId: true,
    amount: true,
    date: true,
    method: true,
    reference: false,
    subsidiaryId: true,
    currencyId: true,
  },
  creditMemoCreate: {
    customerId: true,
    invoiceId: false,
    subsidiaryId: true,
    currencyId: true,
    status: true,
    date: true,
    reason: false,
    notes: false,
  },
  customerRefundCreate: {
    customerId: true,
    cashReceiptId: false,
    bankAccountId: false,
    amount: true,
    date: true,
    method: true,
    reference: false,
    notes: false,
    status: true,
    subsidiaryId: true,
    currencyId: true,
  },
  vendorRefundCreate: {
    vendorId: true,
    billPaymentId: false,
    bankAccountId: false,
    amount: true,
    date: true,
    method: true,
    reference: false,
    notes: false,
    status: true,
    subsidiaryId: true,
    currencyId: true,
  },
  purchaseRequisitionCreate: {
    number: false,
    status: true,
    priority: false,
    title: true,
    description: false,
    neededByDate: true,
    notes: false,
    vendorId: true,
    departmentId: true,
    subsidiaryId: true,
    currencyId: true,
  },
  purchaseOrderCreate: {
    number: false,
    vendorId: true,
    subsidiaryId: true,
    currencyId: true,
    status: true,
  },
  receiptCreate: {
    purchaseOrderId: true,
    quantity: true,
    date: true,
    status: true,
    notes: false,
    subsidiaryId: true,
    currencyId: true,
  },
  billCreate: {
    number: false,
    vendorId: true,
    purchaseOrderId: false,
    subsidiaryId: true,
    currencyId: true,
    total: false,
    date: true,
    dueDate: false,
    status: true,
    notes: false,
  },
  billCreditCreate: {
    vendorId: true,
    billId: false,
    subsidiaryId: true,
    currencyId: true,
    status: true,
    date: true,
    reason: false,
    notes: false,
  },
  billPaymentCreate: {
    billId: true,
    amount: true,
    date: true,
    method: true,
    status: true,
    reference: false,
    notes: false,
    subsidiaryId: true,
    currencyId: true,
  },
  journalCreate: {
    number: false,
    date: true,
    description: false,
    total: false,
    status: true,
    subsidiaryId: true,
    currencyId: true,
    accountingPeriodId: false,
    sourceType: false,
    sourceId: false,
    postedByEmployeeId: false,
    approvedByEmployeeId: false,
  },
  itemCreate: {
    name: true,
    itemId: false,
    externalId: false,
    sku: false,
    salesDescription: false,
    purchaseDescription: false,
    itemType: false,
    itemCategory: false,
    uom: false,
    primaryPurchaseUnit: false,
    primarySaleUnit: false,
    primaryUnitsType: false,
    listPrice: false,
    revenueStream: false,
    recognitionMethod: false,
    recognitionTrigger: false,
    defaultRevRecTemplateId: false,
    defaultTermMonths: false,
    createRevenueArrangementOn: false,
    createForecastPlanOn: false,
    createRevenuePlanOn: false,
    allocationEligible: false,
    performanceObligationType: false,
    standaloneSellingPrice: false,
    billingType: false,
    billingTrigger: false,
    standardCost: false,
    averageCost: false,
    subsidiaryIds: false,
    includeChildren: false,
    departmentId: false,
    locationId: false,
    line: false,
    productLine: false,
    dropShipItem: false,
    specialOrderItem: false,
    canBeFulfilled: false,
    preferredVendorId: false,
    currencyId: false,
    incomeAccountId: false,
    deferredRevenueAccountId: false,
    inventoryAccountId: false,
    cogsExpenseAccountId: false,
    deferredCostAccountId: false,
  },
  currencyCreate: {
    currencyId: true,
    code: true,
    name: true,
    symbol: true,
    decimals: false,
    isBase: false,
    inactive: false,
  },
  accountingPeriodCreate: {
    name: true,
    startDate: true,
    endDate: true,
    subsidiaryId: false,
    status: false,
    closed: false,
    arLocked: false,
    apLocked: false,
    inventoryLocked: false,
  },
  locationCreate: {
    locationId: true,
    code: true,
    name: true,
    subsidiaryId: false,
    parentLocationId: false,
    locationType: false,
    makeInventoryAvailable: false,
    address: false,
    inactive: false,
  },
  chartOfAccountCreate: {
    accountId: true,
    accountNumber: true,
    name: true,
    description: false,
    accountType: true,
    normalBalance: false,
    financialStatementSection: false,
    financialStatementGroup: false,
    financialStatementCategory: false,
    accountRole: false,
    rollforwardCategory: false,
    subsidiaryIds: false,
    includeChildren: false,
    parentAccountId: false,
    closeToAccountId: false,
    isPosting: false,
    isControlAccount: false,
    allowsManualPosting: false,
    requiresSubledgerType: false,
    cashFlowCategory: false,
    inventory: false,
    revalueOpenBalance: false,
    eliminateIntercoTransactions: false,
    summary: false,
  },
  departmentCreate: {
    departmentId: true,
    departmentNumber: false,
    name: true,
    description: false,
    division: false,
    subsidiaryIds: false,
    includeChildren: false,
    planningCategory: false,
    managerEmployeeId: false,
    approverEmployeeId: false,
    inactive: false,
  },
  employeeCreate: {
    employeeId: false,
    eid: false,
    firstName: true,
    lastName: true,
    email: false,
    phone: false,
    title: false,
    laborType: false,
    departmentId: false,
    subsidiaryIds: false,
    includeChildren: false,
    managerId: false,
    userId: false,
    hireDate: false,
    terminationDate: false,
    inactive: false,
  },
  subsidiaryCreate: {
    subsidiaryId: false,
    name: true,
    legalName: false,
    entityType: false,
    country: false,
    address: false,
    taxId: false,
    registrationNumber: false,
    parentSubsidiaryId: false,
      localCurrencyId: false,
      functionalCurrencyId: false,
      groupCurrencyId: false,
    consolidationMethod: false,
    ownershipPercent: false,
    retainedEarningsAccountId: false,
    ctaAccountId: false,
    intercompanyClearingAccountId: false,
    dueToAccountId: false,
    dueFromAccountId: false,
    inactive: false,
  },
  roleCreate: {
    roleId: false,
    name: true,
    description: false,
    inactive: false,
  },
  userCreate: {
    userId: false,
    name: true,
    email: true,
    password: true,
    roleId: false,
    departmentId: false,
    defaultSubsidiaryId: false,
    subsidiaryIds: false,
    includeChildren: false,
    approvalLimit: false,
    approvalCurrencyId: false,
    delegatedApproverUserId: false,
    delegationStartDate: false,
    delegationEndDate: false,
    employeeId: false,
    locked: false,
    mustChangePassword: false,
    failedLoginAttempts: false,
    lastLoginAt: false,
    passwordChangedAt: false,
    inactive: false,
  },
}

export const FORM_LABELS: Record<FormKey, string> = {
  customerCreate: 'Customer',
  contactCreate: 'Contact',
  vendorCreate: 'Vendor',
  leadCreate: 'Lead',
  opportunityCreate: 'Opportunity',
  quoteCreate: 'Quote',
  salesOrderCreate: 'Sales Order',
  fulfillmentCreate: 'Fulfillment',
  invoiceCreate: 'Invoice',
  invoiceReceiptCreate: 'Invoice Receipt',
  creditMemoCreate: 'Credit Memo',
  customerRefundCreate: 'Customer Refund',
  vendorRefundCreate: 'Vendor Refund',
  purchaseRequisitionCreate: 'Purchase Requisition',
  purchaseOrderCreate: 'Purchase Order',
  receiptCreate: 'Receipt',
  billCreate: 'Bill',
  billCreditCreate: 'Bill Credit',
  billPaymentCreate: 'Bill Payment',
  journalCreate: 'Journal Entry',
  itemCreate: 'Item',
  currencyCreate: 'Currency',
  accountingPeriodCreate: 'Accounting Period',
  locationCreate: 'Location',
  chartOfAccountCreate: 'Chart Of Account',
  departmentCreate: 'Department',
  employeeCreate: 'Employee',
  subsidiaryCreate: 'Subsidiary',
  roleCreate: 'Role',
  userCreate: 'User',
}

export const FORM_FIELD_LABELS: Record<FormKey, Record<string, string>> = {
  customerCreate: {
    customerId: 'Customer ID',
    name: 'Customer name',
    email: 'Customer email',
    phone: 'Customer phone',
    address: 'Address',
    industry: 'Industry',
    primarySubsidiaryId: 'Primary subsidiary',
    primaryCurrencyId: 'Primary currency',
    inactive: 'Inactive',
    primaryContact: 'At least one primary contact',
    contactFirstName: 'Primary contact first name',
    contactLastName: 'Primary contact last name',
    addressStreet1: 'Address street line 1',
    addressCity: 'Address city',
    addressStateProvince: 'Address state/province',
    addressPostalCode: 'Address postal code',
    addressCountry: 'Address country',
  },
  contactCreate: {
    contactNumber: 'Contact ID',
    firstName: 'First name',
    lastName: 'Last name',
    customerId: 'Customer',
    vendorId: 'Vendor',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    position: 'Position',
    inactive: 'Inactive',
  },
  vendorCreate: {
    vendorNumber: 'Vendor ID',
    name: 'Vendor name',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    taxId: 'Tax ID',
    primarySubsidiaryId: 'Primary subsidiary',
    primaryCurrencyId: 'Primary currency',
    inactive: 'Inactive',
  },
  leadCreate: {
    firstName: 'First name',
    lastName: 'Last name',
    email: 'Email',
    phone: 'Phone',
    company: 'Company',
    title: 'Title',
    website: 'Website',
    industry: 'Industry',
    status: 'Status',
    source: 'Source',
    rating: 'Rating',
    expectedValue: 'Expected value',
    subsidiaryId: 'Subsidiary',
    currencyId: 'Currency',
    address: 'Address',
    notes: 'Notes',
    lastContactedAt: 'Last contacted',
    qualifiedAt: 'Qualified at',
    convertedAt: 'Converted at',
  },
  opportunityCreate: {
    name: 'Opportunity name',
    customerId: 'Customer',
    amount: 'Amount',
    stage: 'Stage',
    closeDate: 'Close date',
  },
  quoteCreate: {
    opportunity: 'Opportunity',
    customerId: 'Customer',
    number: 'Quote ID',
    status: 'Status',
    validUntil: 'Valid until',
    subsidiaryId: 'Subsidiary',
    currencyId: 'Currency',
    notes: 'Notes',
  },
  salesOrderCreate: {
    customerId: 'Customer',
    userId: 'Created by',
    quoteId: 'Quote',
    number: 'Sales Order ID',
    subsidiaryId: 'Subsidiary',
    currencyId: 'Currency',
    status: 'Status',
    total: 'Total',
  },
  fulfillmentCreate: {
    salesOrderId: 'Sales order',
    status: 'Status',
    date: 'Fulfillment date',
    notes: 'Notes',
    subsidiaryId: 'Subsidiary',
    currencyId: 'Currency',
  },
  invoiceCreate: {
    salesOrderId: 'Sales order',
    customerId: 'Customer',
    status: 'Status',
    dueDate: 'Due date',
    paidDate: 'Paid date',
    subsidiaryId: 'Subsidiary',
    currencyId: 'Currency',
  },
  invoiceReceiptCreate: {
    invoiceId: 'Invoice',
    amount: 'Amount',
    date: 'Receipt date',
    method: 'Method',
    reference: 'Reference',
  },
  creditMemoCreate: {
    customerId: 'Customer',
    invoiceId: 'Invoice',
    subsidiaryId: 'Subsidiary',
    currencyId: 'Currency',
    status: 'Status',
    date: 'Date',
    reason: 'Reason',
    notes: 'Notes',
  },
  customerRefundCreate: {
    customerId: 'Customer',
    cashReceiptId: 'Refund source',
    bankAccountId: 'Bank account',
    amount: 'Amount',
    date: 'Refund date',
    method: 'Method',
    reference: 'Reference',
    notes: 'Notes',
    status: 'Status',
  },
  vendorRefundCreate: {
    vendorId: 'Vendor',
    billPaymentId: 'Refund source',
    bankAccountId: 'Bank account',
    amount: 'Amount',
    date: 'Refund date',
    method: 'Method',
    reference: 'Reference',
    notes: 'Notes',
    status: 'Status',
  },
  purchaseRequisitionCreate: {
    number: 'Purchase requisition ID',
    status: 'Status',
    priority: 'Priority',
    title: 'Title',
    description: 'Description',
    neededByDate: 'Needed by date',
    notes: 'Notes',
    vendorId: 'Vendor',
    departmentId: 'Department',
    subsidiaryId: 'Subsidiary',
    currencyId: 'Currency',
  },
  purchaseOrderCreate: {
    number: 'Purchase order ID',
    vendorId: 'Vendor',
    subsidiaryId: 'Subsidiary',
    status: 'Status',
  },
  receiptCreate: {
    purchaseOrderId: 'Purchase order',
    quantity: 'Quantity',
    date: 'Date',
    status: 'Status',
    notes: 'Notes',
  },
  billCreate: {
    number: 'Bill ID',
    vendorId: 'Vendor',
    purchaseOrderId: 'Purchase order',
    subsidiaryId: 'Subsidiary',
    currencyId: 'Currency',
    total: 'Total',
    date: 'Bill date',
    dueDate: 'Due date',
    status: 'Status',
    notes: 'Notes',
  },
  billCreditCreate: {
    vendorId: 'Vendor',
    billId: 'Bill',
    subsidiaryId: 'Subsidiary',
    currencyId: 'Currency',
    status: 'Status',
    date: 'Date',
    reason: 'Reason',
    notes: 'Notes',
  },
  billPaymentCreate: {
    billId: 'Bill',
    amount: 'Amount',
    date: 'Date',
    method: 'Method',
    status: 'Status',
    reference: 'Reference',
    notes: 'Notes',
  },
  journalCreate: {
    number: 'Journal number',
    date: 'Date',
    description: 'Description',
    total: 'Total',
    status: 'Status',
    subsidiaryId: 'Header subsidiary',
    currencyId: 'Currency',
    accountingPeriodId: 'Accounting period',
    sourceType: 'Source type',
    sourceId: 'Source ID',
    postedByEmployeeId: 'Prepared by',
    approvedByEmployeeId: 'Approved by',
  },
  itemCreate: {
    name: 'Item name',
    itemId: 'Item ID',
    externalId: 'External ID',
    sku: 'SKU',
    salesDescription: 'Sales description',
    purchaseDescription: 'Purchase description',
    itemType: 'Item type',
    itemCategory: 'Item category',
    uom: 'Unit of measure',
    primaryPurchaseUnit: 'Primary purchase unit',
    primarySaleUnit: 'Primary sales unit',
    primaryUnitsType: 'Primary units type',
    listPrice: 'List price',
    revenueStream: 'Revenue stream',
    recognitionMethod: 'Recognition method',
    recognitionTrigger: 'Recognition trigger',
    defaultRevRecTemplateId: 'Revenue recognition template',
    defaultTermMonths: 'Default term months',
    createRevenueArrangementOn: 'Create revenue arrangement on',
    createForecastPlanOn: 'Create forecast plan on',
    createRevenuePlanOn: 'Create revenue plan on',
    allocationEligible: 'Allocation eligible',
    performanceObligationType: 'Performance obligation type',
    standaloneSellingPrice: 'Standalone selling price',
    billingType: 'Billing type',
    billingTrigger: 'Billing trigger',
    standardCost: 'Standard cost',
    averageCost: 'Average cost',
    subsidiaryIds: 'Subsidiaries',
    includeChildren: 'Include Children',
    departmentId: 'Department Id',
    locationId: 'Location Id',
    line: 'Business Line',
    productLine: 'Product Line',
    dropShipItem: 'Drop Ship Item',
    specialOrderItem: 'Special Order Item',
    canBeFulfilled: 'Can Be Fulfilled',
    preferredVendorId: 'Preferred Vendor Id',
    currencyId: 'Currency',
    incomeAccountId: 'Income account',
    deferredRevenueAccountId: 'Deferred revenue account',
    inventoryAccountId: 'Asset account',
    cogsExpenseAccountId: 'COGS / expense account',
    deferredCostAccountId: 'Deferred cost account',
  },
  currencyCreate: {
    currencyId: 'Currency ID',
    code: 'Code',
    name: 'Name',
    symbol: 'Symbol',
    decimals: 'Decimal places',
    isBase: 'Base currency',
    inactive: 'Inactive',
  },
  accountingPeriodCreate: {
    name: 'Name',
    startDate: 'Start Date',
    endDate: 'End Date',
    subsidiaryId: 'Subsidiary',
    status: 'Status',
    closed: 'Closed',
    arLocked: 'AR Locked',
    apLocked: 'AP Locked',
    inventoryLocked: 'Inventory Locked',
  },
  locationCreate: {
    locationId: 'Location ID',
    code: 'Code',
    name: 'Name',
    subsidiaryId: 'Subsidiary',
    parentLocationId: 'Parent Location',
    locationType: 'Location Type',
    makeInventoryAvailable: 'Make Inventory Available',
    address: 'Address',
    inactive: 'Inactive',
  },
  chartOfAccountCreate: {
    accountId: 'Account ID',
    accountNumber: 'Account Number',
    name: 'Name',
    description: 'Description',
    accountType: 'Account type',
    normalBalance: 'Normal balance',
    financialStatementSection: 'Financial statement section',
    financialStatementGroup: 'Financial statement group',
    financialStatementCategory: 'Financial statement category',
    accountRole: 'Account role',
    rollforwardCategory: 'Rollforward category',
    subsidiaryIds: 'Subsidiaries',
    includeChildren: 'Include children',
    parentAccountId: 'Parent account',
    closeToAccountId: 'Close to account',
    isPosting: 'Posting account',
    isControlAccount: 'Control account',
    allowsManualPosting: 'Allow manual posting',
    requiresSubledgerType: 'Requires subledger type',
    cashFlowCategory: 'Cash flow category',
    inventory: 'Inventory',
    revalueOpenBalance: 'Revalue open balance',
    eliminateIntercoTransactions: 'Eliminate intercompany transactions',
    summary: 'Summary',
  },
  departmentCreate: {
    departmentId: 'Department ID',
    departmentNumber: 'Department Number',
    name: 'Name',
    description: 'Description',
    division: 'Division',
    subsidiaryIds: 'Subsidiaries',
    includeChildren: 'Include Children',
    planningCategory: 'Department Planning Category',
    managerEmployeeId: 'Department Manager',
    approverEmployeeId: 'Department Approver',
    inactive: 'Inactive',
  },
  employeeCreate: {
    employeeId: 'Employee ID',
    eid: 'EID',
    firstName: 'First name',
    lastName: 'Last name',
    email: 'Email',
    phone: 'Phone',
    title: 'Title',
    laborType: 'Labor Type',
    departmentId: 'Department',
    subsidiaryIds: 'Subsidiaries',
    includeChildren: 'Include Children',
    managerId: 'Manager',
    userId: 'Linked user',
    hireDate: 'Hire date',
    terminationDate: 'Termination date',
    inactive: 'Inactive',
  },
  subsidiaryCreate: {
    subsidiaryId: 'Subsidiary ID',
    name: 'Name',
    legalName: 'Legal name',
    entityType: 'Type',
    country: 'Country',
    address: 'Address',
    taxId: 'Tax ID',
    registrationNumber: 'Registration number',
    parentSubsidiaryId: 'Parent subsidiary',
      localCurrencyId: 'Local currency',
      functionalCurrencyId: 'Functional currency',
      groupCurrencyId: 'Group currency',
    consolidationMethod: 'Consolidation method',
    ownershipPercent: 'Ownership percent',
    retainedEarningsAccountId: 'Retained earnings account',
    ctaAccountId: 'CTA account',
    intercompanyClearingAccountId: 'Intercompany clearing account',
    dueToAccountId: 'Due to account',
    dueFromAccountId: 'Due from account',
    inactive: 'Inactive',
  },
  roleCreate: {
    roleId: 'Role ID',
    name: 'Name',
    description: 'Description',
    inactive: 'Inactive',
  },
  userCreate: {
    userId: 'User ID',
    name: 'Name',
    email: 'Email',
    password: 'Password',
    roleId: 'Role',
    departmentId: 'Department',
    defaultSubsidiaryId: 'Default subsidiary',
    subsidiaryIds: 'Subsidiaries',
    includeChildren: 'Include children',
    approvalLimit: 'Approval limit',
    approvalCurrencyId: 'Approval currency',
    delegatedApproverUserId: 'Delegated approver',
    delegationStartDate: 'Delegation start date',
    delegationEndDate: 'Delegation end date',
    employeeId: 'Linked employee',
    locked: 'Locked',
    mustChangePassword: 'Must change password',
    failedLoginAttempts: 'Failed login attempts',
    lastLoginAt: 'Last login',
    passwordChangedAt: 'Password changed',
    inactive: 'Inactive',
  },
}

export const LOCKED_FORM_REQUIREMENTS: Partial<FormRequirementsMap> = {
  opportunityCreate: {
    name: true,
    customerId: true,
    subsidiaryId: true,
    currencyId: true,
  },
  quoteCreate: {
    opportunity: true,
    subsidiaryId: true,
    currencyId: true,
  },
  salesOrderCreate: {
    customerId: true,
    subsidiaryId: true,
    currencyId: true,
  },
  fulfillmentCreate: {
    salesOrderId: true,
    subsidiaryId: true,
    currencyId: true,
  },
  invoiceCreate: {
    customerId: true,
    status: true,
    dueDate: true,
    subsidiaryId: true,
    currencyId: true,
  },
  invoiceReceiptCreate: {
    invoiceId: true,
    amount: true,
    date: true,
    method: true,
    subsidiaryId: true,
    currencyId: true,
  },
  creditMemoCreate: {
    customerId: true,
    subsidiaryId: true,
    currencyId: true,
    status: true,
    date: true,
  },
  customerRefundCreate: {
    customerId: true,
    amount: true,
    date: true,
    method: true,
    status: true,
    subsidiaryId: true,
    currencyId: true,
  },
  vendorRefundCreate: {
    vendorId: true,
    amount: true,
    date: true,
    method: true,
    status: true,
    subsidiaryId: true,
    currencyId: true,
  },
  purchaseRequisitionCreate: {
    title: true,
    neededByDate: true,
    vendorId: true,
    departmentId: true,
    subsidiaryId: true,
    currencyId: true,
  },
  purchaseOrderCreate: {
    vendorId: true,
    subsidiaryId: true,
    currencyId: true,
  },
  receiptCreate: {
    purchaseOrderId: true,
    quantity: true,
    subsidiaryId: true,
    currencyId: true,
  },
  billCreate: {
    vendorId: true,
    date: true,
    subsidiaryId: true,
    currencyId: true,
  },
  billCreditCreate: {
    vendorId: true,
    subsidiaryId: true,
    currencyId: true,
    status: true,
    date: true,
  },
  billPaymentCreate: {
    billId: true,
    amount: true,
    date: true,
    method: true,
    subsidiaryId: true,
    currencyId: true,
  },
  journalCreate: {
    date: true,
    subsidiaryId: true,
    currencyId: true,
  },
}

export function isFieldRequired(form: FormKey, field: string): boolean {
  return Boolean(FORM_REQUIREMENTS[form]?.[field])
}

export function isFieldRequirementLocked(form: FormKey, field: string): boolean {
  return Boolean(LOCKED_FORM_REQUIREMENTS[form]?.[field])
}
