export type FormKey = 'customerCreate' | 'contactCreate' | 'vendorCreate' | 'opportunityCreate' | 'itemCreate' | 'currencyCreate' | 'locationCreate' | 'chartOfAccountCreate' | 'departmentCreate' | 'employeeCreate' | 'subsidiaryCreate' | 'roleCreate' | 'userCreate'

export type FormRequirements = Record<string, boolean>
export type FormRequirementsMap = Record<FormKey, FormRequirements>

/**
 * Centralized required-field configuration by form.
 * Toggle booleans here to change required fields per company preference.
 */
export const FORM_REQUIREMENTS: FormRequirementsMap = {
  customerCreate: {
    customerId: false,
    name: true,
    email: true,
    phone: true,
    address: true,
    industry: false,
    primarySubsidiaryId: false,
    primaryCurrencyId: false,
    inactive: false,
    primaryContact: true,
    contactFirstName: true,
    contactLastName: true,
    addressStreet1: true,
    addressCity: true,
    addressStateProvince: true,
    addressPostalCode: true,
    addressCountry: true,
  },
  contactCreate: {
    contactNumber: false,
    firstName: true,
    lastName: true,
    customerId: false,
    vendorId: false,
    email: false,
    phone: false,
    address: false,
    position: false,
    inactive: false,
  },
  vendorCreate: {
    vendorNumber: false,
    name: true,
    email: false,
    phone: false,
    address: false,
    taxId: false,
    primarySubsidiaryId: false,
    primaryCurrencyId: false,
    inactive: false,
  },
  opportunityCreate: {
    name: true,
    customerId: true,
    amount: false,
    stage: false,
    closeDate: false,
  },
  itemCreate: {
    name: true,
    itemId: false,
    sku: false,
    salesDescription: false,
    purchaseDescription: false,
    itemType: false,
    itemCategory: false,
    uom: false,
    primaryPurchaseUnit: false,
    primarySaleUnit: false,
    primaryUnitsType: false,
    listPrice: false,
    revenueStream: false,
    recognitionMethod: false,
    recognitionTrigger: false,
    defaultRevRecTemplateId: false,
    defaultTermMonths: false,
    createRevenueArrangementOn: false,
    createForecastPlanOn: false,
    createRevenuePlanOn: false,
    allocationEligible: false,
    performanceObligationType: false,
    standaloneSellingPrice: false,
    billingType: false,
    standardCost: false,
    averageCost: false,
    subsidiaryIds: false,
    includeChildren: false,
    departmentId: false,
    locationId: false,
    line: false,
    productLine: false,
    dropShipItem: false,
    specialOrderItem: false,
    canBeFulfilled: false,
    preferredVendorId: false,
    currencyId: false,
    incomeAccountId: false,
    deferredRevenueAccountId: false,
    inventoryAccountId: false,
    cogsExpenseAccountId: false,
    deferredCostAccountId: false,
  },
  currencyCreate: {
    currencyId: true,
    code: true,
    name: true,
    symbol: true,
    decimals: false,
    isBase: false,
    inactive: false,
  },
  locationCreate: {
    locationId: true,
    code: true,
    name: true,
    subsidiaryId: false,
    parentLocationId: false,
    locationType: false,
    makeInventoryAvailable: false,
    address: false,
    inactive: false,
  },
  chartOfAccountCreate: {
    accountId: true,
    accountNumber: true,
    name: true,
    description: false,
    accountType: true,
    normalBalance: false,
    financialStatementSection: false,
    financialStatementGroup: false,
    subsidiaryIds: false,
    includeChildren: false,
    parentAccountId: false,
    closeToAccountId: false,
    isPosting: false,
    isControlAccount: false,
    allowsManualPosting: false,
    requiresSubledgerType: false,
    cashFlowCategory: false,
    inventory: false,
    revalueOpenBalance: false,
    eliminateIntercoTransactions: false,
    summary: false,
  },
  departmentCreate: {
    departmentId: true,
    departmentNumber: false,
    name: true,
    description: false,
    division: false,
    subsidiaryIds: false,
    includeChildren: false,
    planningCategory: false,
    managerEmployeeId: false,
    approverEmployeeId: false,
    inactive: false,
  },
  employeeCreate: {
    employeeId: false,
    eid: false,
    firstName: true,
    lastName: true,
    email: false,
    phone: false,
    title: false,
    laborType: false,
    departmentId: false,
    subsidiaryIds: false,
    includeChildren: false,
    managerId: false,
    userId: false,
    hireDate: false,
    terminationDate: false,
    inactive: false,
  },
  subsidiaryCreate: {
    subsidiaryId: false,
    name: true,
    legalName: false,
    entityType: false,
    country: false,
    address: false,
    taxId: false,
    registrationNumber: false,
    parentSubsidiaryId: false,
    defaultCurrencyId: false,
    functionalCurrencyId: false,
    reportingCurrencyId: false,
    consolidationMethod: false,
    ownershipPercent: false,
    retainedEarningsAccountId: false,
    ctaAccountId: false,
    intercompanyClearingAccountId: false,
    dueToAccountId: false,
    dueFromAccountId: false,
    inactive: false,
  },
  roleCreate: {
    roleId: false,
    name: true,
    description: false,
    inactive: false,
  },
  userCreate: {
    userId: false,
    name: true,
    email: true,
    password: true,
    roleId: false,
    departmentId: false,
    defaultSubsidiaryId: false,
    subsidiaryIds: false,
    includeChildren: false,
    approvalLimit: false,
    approvalCurrencyId: false,
    delegatedApproverUserId: false,
    delegationStartDate: false,
    delegationEndDate: false,
    employeeId: false,
    locked: false,
    mustChangePassword: false,
    failedLoginAttempts: false,
    lastLoginAt: false,
    passwordChangedAt: false,
    inactive: false,
  },
}

export const FORM_LABELS: Record<FormKey, string> = {
  customerCreate: 'Customer',
  contactCreate: 'Contact',
  vendorCreate: 'Vendor',
  opportunityCreate: 'Opportunity',
  itemCreate: 'Item',
  currencyCreate: 'Currency',
  locationCreate: 'Location',
  chartOfAccountCreate: 'Chart Of Account',
  departmentCreate: 'Department',
  employeeCreate: 'Employee',
  subsidiaryCreate: 'Subsidiary',
  roleCreate: 'Role',
  userCreate: 'User',
}

export const FORM_FIELD_LABELS: Record<FormKey, Record<string, string>> = {
  customerCreate: {
    customerId: 'Customer ID',
    name: 'Customer name',
    email: 'Customer email',
    phone: 'Customer phone',
    address: 'Address',
    industry: 'Industry',
    primarySubsidiaryId: 'Primary subsidiary',
    primaryCurrencyId: 'Primary currency',
    inactive: 'Inactive',
    primaryContact: 'At least one primary contact',
    contactFirstName: 'Primary contact first name',
    contactLastName: 'Primary contact last name',
    addressStreet1: 'Address street line 1',
    addressCity: 'Address city',
    addressStateProvince: 'Address state/province',
    addressPostalCode: 'Address postal code',
    addressCountry: 'Address country',
  },
  contactCreate: {
    contactNumber: 'Contact ID',
    firstName: 'First name',
    lastName: 'Last name',
    customerId: 'Customer',
    vendorId: 'Vendor',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    position: 'Position',
    inactive: 'Inactive',
  },
  vendorCreate: {
    vendorNumber: 'Vendor ID',
    name: 'Vendor name',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    taxId: 'Tax ID',
    primarySubsidiaryId: 'Primary subsidiary',
    primaryCurrencyId: 'Primary currency',
    inactive: 'Inactive',
  },
  opportunityCreate: {
    name: 'Opportunity name',
    customerId: 'Customer',
    amount: 'Amount',
    stage: 'Stage',
    closeDate: 'Close date',
  },
  itemCreate: {
    name: 'Item name',
    itemId: 'Item ID',
    sku: 'SKU',
    salesDescription: 'Sales description',
    purchaseDescription: 'Purchase description',
    itemType: 'Item type',
    itemCategory: 'Item category',
    uom: 'Unit of measure',
    primaryPurchaseUnit: 'Primary purchase unit',
    primarySaleUnit: 'Primary sales unit',
    primaryUnitsType: 'Primary units type',
    listPrice: 'List price',
    revenueStream: 'Revenue stream',
    recognitionMethod: 'Recognition method',
    recognitionTrigger: 'Recognition trigger',
    defaultRevRecTemplateId: 'Revenue recognition template',
    defaultTermMonths: 'Default term months',
    createRevenueArrangementOn: 'Create revenue arrangement on',
    createForecastPlanOn: 'Create forecast plan on',
    createRevenuePlanOn: 'Create revenue plan on',
    allocationEligible: 'Allocation eligible',
    performanceObligationType: 'Performance obligation type',
    standaloneSellingPrice: 'Standalone selling price',
    billingType: 'Billing type',
    standardCost: 'Standard cost',
    averageCost: 'Average cost',
    subsidiaryIds: 'Subsidiaries',
    includeChildren: 'Include Children',
    departmentId: 'Department Id',
    locationId: 'Location Id',
    line: 'Line',
    productLine: 'Product Line',
    dropShipItem: 'Drop Ship Item',
    specialOrderItem: 'Special Order Item',
    canBeFulfilled: 'Can Be Fulfilled',
    preferredVendorId: 'Preferred Vendor Id',
    currencyId: 'Currency',
    incomeAccountId: 'Income account',
    deferredRevenueAccountId: 'Deferred revenue account',
    inventoryAccountId: 'Asset account',
    cogsExpenseAccountId: 'COGS / expense account',
    deferredCostAccountId: 'Deferred cost account',
  },
  currencyCreate: {
    currencyId: 'Currency ID',
    code: 'Code',
    name: 'Name',
    symbol: 'Symbol',
    decimals: 'Decimal places',
    isBase: 'Base currency',
    inactive: 'Inactive',
  },
  locationCreate: {
    locationId: 'Location ID',
    code: 'Code',
    name: 'Name',
    subsidiaryId: 'Subsidiary',
    parentLocationId: 'Parent Location',
    locationType: 'Location Type',
    makeInventoryAvailable: 'Make Inventory Available',
    address: 'Address',
    inactive: 'Inactive',
  },
  chartOfAccountCreate: {
    accountId: 'Account ID',
    accountNumber: 'Account Number',
    name: 'Name',
    description: 'Description',
    accountType: 'Account type',
    normalBalance: 'Normal balance',
    financialStatementSection: 'Financial statement section',
    financialStatementGroup: 'Financial statement group',
    subsidiaryIds: 'Subsidiaries',
    includeChildren: 'Include children',
    parentAccountId: 'Parent account',
    closeToAccountId: 'Close to account',
    isPosting: 'Posting account',
    isControlAccount: 'Control account',
    allowsManualPosting: 'Allow manual posting',
    requiresSubledgerType: 'Requires subledger type',
    cashFlowCategory: 'Cash flow category',
    inventory: 'Inventory',
    revalueOpenBalance: 'Revalue open balance',
    eliminateIntercoTransactions: 'Eliminate intercompany transactions',
    summary: 'Summary',
  },
  departmentCreate: {
    departmentId: 'Department ID',
    departmentNumber: 'Department Number',
    name: 'Name',
    description: 'Description',
    division: 'Division',
    subsidiaryIds: 'Subsidiaries',
    includeChildren: 'Include Children',
    planningCategory: 'Department Planning Category',
    managerEmployeeId: 'Department Manager',
    approverEmployeeId: 'Department Approver',
    inactive: 'Inactive',
  },
  employeeCreate: {
    employeeId: 'Employee ID',
    eid: 'EID',
    firstName: 'First name',
    lastName: 'Last name',
    email: 'Email',
    phone: 'Phone',
    title: 'Title',
    laborType: 'Labor Type',
    departmentId: 'Department',
    subsidiaryIds: 'Subsidiaries',
    includeChildren: 'Include Children',
    managerId: 'Manager',
    userId: 'Linked user',
    hireDate: 'Hire date',
    terminationDate: 'Termination date',
    inactive: 'Inactive',
  },
  subsidiaryCreate: {
    subsidiaryId: 'Subsidiary ID',
    name: 'Name',
    legalName: 'Legal name',
    entityType: 'Type',
    country: 'Country',
    address: 'Address',
    taxId: 'Tax ID',
    registrationNumber: 'Registration number',
    parentSubsidiaryId: 'Parent subsidiary',
    defaultCurrencyId: 'Primary currency',
    functionalCurrencyId: 'Functional currency',
    reportingCurrencyId: 'Reporting currency',
    consolidationMethod: 'Consolidation method',
    ownershipPercent: 'Ownership percent',
    retainedEarningsAccountId: 'Retained earnings account',
    ctaAccountId: 'CTA account',
    intercompanyClearingAccountId: 'Intercompany clearing account',
    dueToAccountId: 'Due to account',
    dueFromAccountId: 'Due from account',
    inactive: 'Inactive',
  },
  roleCreate: {
    roleId: 'Role ID',
    name: 'Name',
    description: 'Description',
    inactive: 'Inactive',
  },
  userCreate: {
    userId: 'User ID',
    name: 'Name',
    email: 'Email',
    password: 'Password',
    roleId: 'Role',
    departmentId: 'Department',
    defaultSubsidiaryId: 'Default subsidiary',
    subsidiaryIds: 'Subsidiaries',
    includeChildren: 'Include children',
    approvalLimit: 'Approval limit',
    approvalCurrencyId: 'Approval currency',
    delegatedApproverUserId: 'Delegated approver',
    delegationStartDate: 'Delegation start date',
    delegationEndDate: 'Delegation end date',
    employeeId: 'Linked employee',
    locked: 'Locked',
    mustChangePassword: 'Must change password',
    failedLoginAttempts: 'Failed login attempts',
    lastLoginAt: 'Last login',
    passwordChangedAt: 'Password changed',
    inactive: 'Inactive',
  },
}

export function isFieldRequired(form: FormKey, field: string): boolean {
  return Boolean(FORM_REQUIREMENTS[form]?.[field])
}
