// Generated by sync-transaction-framework

import { promises as fs } from 'fs'
import path from 'path'
import {
  defaultInvoiceReceiptDetailCustomization,
  type InvoiceReceiptDetailCustomizationConfig,
} from '@/lib/invoice-receipt-detail-customization'

const STORE_PATH = path.join(process.cwd(), 'config', 'invoice-receipt-detail-customization.json')

function cloneDefaults(): InvoiceReceiptDetailCustomizationConfig {
  return JSON.parse(JSON.stringify(defaultInvoiceReceiptDetailCustomization())) as InvoiceReceiptDetailCustomizationConfig
}

export async function loadInvoiceReceiptDetailCustomization(): Promise<InvoiceReceiptDetailCustomizationConfig> {
  try {
    const raw = await fs.readFile(STORE_PATH, 'utf8')
    return { ...cloneDefaults(), ...(JSON.parse(raw) as Partial<InvoiceReceiptDetailCustomizationConfig>) }
  } catch {
    return cloneDefaults()
  }
}

export async function saveInvoiceReceiptDetailCustomization(nextConfig: InvoiceReceiptDetailCustomizationConfig): Promise<InvoiceReceiptDetailCustomizationConfig> {
  await fs.mkdir(path.dirname(STORE_PATH), { recursive: true })
  await fs.writeFile(STORE_PATH, `${JSON.stringify(nextConfig, null, 2)}\n`, 'utf8')
  return nextConfig
}
