CREATE TABLE "document_relationships" (
    "id" TEXT NOT NULL,
    "sourceRecordType" TEXT NOT NULL,
    "sourceRecordId" TEXT NOT NULL,
    "targetRecordType" TEXT NOT NULL,
    "targetRecordId" TEXT NOT NULL,
    "relationshipType" TEXT NOT NULL,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "automationSource" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "document_relationships_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "document_relationships_sourceRecordType_sourceRecordId_targetRecordType_targetRecordId_relationshipType_key"
ON "document_relationships"("sourceRecordType", "sourceRecordId", "targetRecordType", "targetRecordId", "relationshipType");

CREATE INDEX "document_relationships_sourceRecordType_sourceRecordId_idx"
ON "document_relationships"("sourceRecordType", "sourceRecordId");

CREATE INDEX "document_relationships_targetRecordType_targetRecordId_idx"
ON "document_relationships"("targetRecordType", "targetRecordId");

CREATE INDEX "document_relationships_relationshipType_idx"
ON "document_relationships"("relationshipType");
