// Generated by sync-transaction-framework
'use client'

import type { InvoiceReceiptDetailCustomizationConfig, InvoiceReceiptDetailFieldKey } from '@/lib/invoice-receipt-detail-customization'
import TransactionDetailCustomizeMode from '@/components/TransactionDetailCustomizeMode'
import { INVOICE_RECEIPT_STAT_CARDS } from '@/lib/invoice-receipt-detail-customization'

type CustomizeField = {
  id: InvoiceReceiptDetailFieldKey
  label: string
  fieldType: string
  source?: string
  description?: string
  previewValue?: string
}

export default function InvoiceReceiptDetailCustomizeMode({
  detailHref,
  initialLayout,
  fields,
  sectionDescriptions,
}: {
  detailHref: string
  initialLayout: InvoiceReceiptDetailCustomizationConfig
  fields: CustomizeField[]
  sectionDescriptions?: Record<string, string>
}) {
  return (
    <TransactionDetailCustomizeMode
      detailHref={detailHref}
      initialLayout={initialLayout}
      fields={fields}
      saveEndpoint="/api/config/invoice-receipt-detail-customization"
      sectionDescriptions={sectionDescriptions}
      statCardDefinitions={INVOICE_RECEIPT_STAT_CARDS}
      statCardsTitle="Stat Cards"
      statCardsIntro="Control which summary cards appear at the top of the invoice receipt detail page and their order."
    />
  )
}
