// Generated by sync-transaction-framework
'use client'

import { useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import RecordDetailPageShell from '@/components/RecordDetailPageShell'
import PurchaseOrderHeaderSections, {
  type PurchaseOrderHeaderField,
  type PurchaseOrderHeaderSection,
} from '@/components/PurchaseOrderHeaderSections'
import PurchaseOrderLineItemsSection from '@/components/PurchaseOrderLineItemsSection'
import { RecordDetailEmptyState, RecordDetailSection } from '@/components/RecordDetailPanels'
import { buildConfiguredTransactionSections } from '@/lib/transaction-detail-helpers'
import {
  INVOICE_DETAIL_FIELDS,
  type InvoiceDetailCustomizationConfig,
  type InvoiceDetailFieldKey,
} from '@/lib/invoice-detail-customization'
import { fmtCurrency, fmtDocumentDate } from '@/lib/format'

type SalesOrderOption = {
  id: string
  number: string
  customer: {
    id: string
    customerId: string | null
    name: string
    email: string | null
    phone: string | null
    address: string | null
    inactive: boolean
    subsidiary: { id: string; subsidiaryId: string; name: string } | null
    currency: { id: string; currencyId: string; code: string; name: string } | null
  }
  user: {
    id: string
    userId: string | null
    name: string | null
    email: string
  } | null
  subsidiary: { id: string; subsidiaryId: string; name: string } | null
  currency: { id: string; currencyId: string; code: string; name: string } | null
  quote: {
    id: string
    number: string
    opportunity: { id: string; opportunityNumber: string | null; name: string } | null
  } | null
  lineItems: Array<{
    id: string
    description: string
    quantity: number
    unitPrice: number
    lineTotal: number
    item: { id: string; itemId: string | null; name: string } | null
  }>
  total: number
}

type CustomerOption = {
  id: string
  customerId: string | null
  name: string
  email: string | null
  phone: string | null
  address: string | null
  inactive: boolean
  subsidiary: { id: string; subsidiaryId: string; name: string } | null
  currency: { id: string; currencyId: string; code: string; name: string } | null
}

type DuplicateInvoiceSource = {
  id: string
  number: string
  status: string
  dueDate: string | null
  paidDate: string | null
  total: number
  customer: CustomerOption
  user: {
    id: string
    userId: string | null
    name: string | null
    email: string
  } | null
  salesOrder: {
    id: string
    number: string
    quote: {
      id: string
      number: string
      opportunity: { id: string; opportunityNumber: string | null; name: string } | null
    } | null
  } | null
  subsidiary: { id: string; subsidiaryId: string; name: string } | null
  currency: { id: string; currencyId: string; code: string; name: string } | null
  lineItems: Array<{
    id: string
    description: string
    quantity: number
    unitPrice: number
    lineTotal: number
    item: { id: string; itemId: string | null; name: string } | null
  }>
}

const sectionDescriptions: Record<string, string> = {
  Customer: 'Customer contact and default commercial context from the selected customer or sales order.',
  'Invoice Details': 'Core invoice fields, upstream sales context, and financial dates.',
}

export default function InvoiceCreatePageClient({
  salesOrders,
  customers,
  subsidiaries,
  currencies,
  customization,
  duplicateFrom,
  duplicateInvoice,
}: {
  salesOrders: SalesOrderOption[]
  customers: CustomerOption[]
  subsidiaries: Array<{ id: string; subsidiaryId: string; name: string }>
  currencies: Array<{ id: string; currencyId: string; code: string; name: string }>
  customization: InvoiceDetailCustomizationConfig
  duplicateFrom?: string
  duplicateInvoice?: DuplicateInvoiceSource | null
}) {
  const router = useRouter()
  const initialSalesOrder = duplicateInvoice ? null : salesOrders[0] ?? null
  const [headerValues, setHeaderValues] = useState<Record<string, string>>({
    salesOrderId: duplicateInvoice?.salesOrder?.id ?? initialSalesOrder?.id ?? '',
    customerId: duplicateInvoice?.customer.id ?? initialSalesOrder?.customer.id ?? '',
    subsidiaryId:
      duplicateInvoice?.subsidiary?.id ??
      duplicateInvoice?.customer.subsidiary?.id ??
      initialSalesOrder?.subsidiary?.id ??
      initialSalesOrder?.customer.subsidiary?.id ??
      '',
    currencyId:
      duplicateInvoice?.currency?.id ??
      duplicateInvoice?.customer.currency?.id ??
      initialSalesOrder?.currency?.id ??
      initialSalesOrder?.customer.currency?.id ??
      '',
    status: 'draft',
    dueDate: duplicateInvoice?.dueDate ?? '',
    paidDate: '',
  })
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')

  const selectedSalesOrder = useMemo(
    () => salesOrders.find((salesOrder) => salesOrder.id === (headerValues.salesOrderId ?? '')) ?? null,
    [headerValues.salesOrderId, salesOrders],
  )

  const selectedCustomer = useMemo(() => {
    if (selectedSalesOrder) return selectedSalesOrder.customer
    if (duplicateInvoice) {
      return customers.find((customer) => customer.id === (headerValues.customerId ?? '')) ?? duplicateInvoice.customer
    }
    return customers.find((customer) => customer.id === (headerValues.customerId ?? '')) ?? null
  }, [customers, duplicateInvoice, headerValues.customerId, selectedSalesOrder])

  const createdByLabel = selectedSalesOrder?.user
    ? selectedSalesOrder.user.userId && selectedSalesOrder.user.name
      ? `${selectedSalesOrder.user.userId} - ${selectedSalesOrder.user.name}`
      : selectedSalesOrder.user.userId ?? selectedSalesOrder.user.name ?? selectedSalesOrder.user.email
    : duplicateInvoice?.user
      ? duplicateInvoice.user.userId && duplicateInvoice.user.name
        ? `${duplicateInvoice.user.userId} - ${duplicateInvoice.user.name}`
        : duplicateInvoice.user.userId ?? duplicateInvoice.user.name ?? duplicateInvoice.user.email
      : '-'

  const salesOrderOptions = salesOrders.map((salesOrder) => ({
    value: salesOrder.id,
    label: `${salesOrder.number} - ${salesOrder.customer.name}`,
  }))
  const customerOptions = customers.map((customer) => ({
    value: customer.id,
    label: `${customer.customerId ?? 'CUSTOMER'} - ${customer.name}`,
  }))
  const subsidiaryOptions = subsidiaries.map((subsidiary) => ({
    value: subsidiary.id,
    label: `${subsidiary.subsidiaryId} - ${subsidiary.name}`,
  }))
  const currencyOptions = currencies.map((currency) => ({
    value: currency.id,
    label: `${currency.code ?? currency.currencyId} - ${currency.name}`,
  }))

  const headerFieldDefinitions: Record<
    InvoiceDetailFieldKey,
    PurchaseOrderHeaderField & { key: InvoiceDetailFieldKey }
  > = {
    customerName: {
      key: 'customerName',
      label: 'Customer Name',
      value: selectedCustomer?.name ?? '',
      displayValue: selectedCustomer?.name ?? '-',
      helpText: 'Display name from the linked customer record.',
      fieldType: 'text',
      sourceText: 'Customers master data',
    },
    customerNumber: {
      key: 'customerNumber',
      label: 'Customer #',
      value: selectedCustomer?.customerId ?? '',
      displayValue: selectedCustomer?.customerId ?? '-',
      helpText: 'Internal customer identifier from the linked customer record.',
      fieldType: 'text',
      sourceText: 'Customers master data',
    },
    customerEmail: {
      key: 'customerEmail',
      label: 'Email',
      value: selectedCustomer?.email ?? '',
      displayValue: selectedCustomer?.email ?? '-',
      helpText: 'Primary customer email address.',
      fieldType: 'email',
      sourceText: 'Customers master data',
    },
    customerPhone: {
      key: 'customerPhone',
      label: 'Phone',
      value: selectedCustomer?.phone ?? '',
      displayValue: selectedCustomer?.phone ?? '-',
      helpText: 'Primary customer phone number.',
      fieldType: 'text',
      sourceText: 'Customers master data',
    },
    customerAddress: {
      key: 'customerAddress',
      label: 'Billing Address',
      value: selectedCustomer?.address ?? '',
      displayValue: selectedCustomer?.address ?? '-',
      helpText: 'Main billing address from the linked customer record.',
      fieldType: 'text',
      sourceText: 'Customers master data',
    },
    customerPrimarySubsidiary: {
      key: 'customerPrimarySubsidiary',
      label: 'Primary Subsidiary',
      value: selectedCustomer?.subsidiary ? `${selectedCustomer.subsidiary.subsidiaryId} - ${selectedCustomer.subsidiary.name}` : '',
      displayValue: selectedCustomer?.subsidiary ? `${selectedCustomer.subsidiary.subsidiaryId} - ${selectedCustomer.subsidiary.name}` : '-',
      helpText: 'Default subsidiary context from the linked customer record.',
      fieldType: 'list',
      sourceText: 'Customers master data',
    },
    customerPrimaryCurrency: {
      key: 'customerPrimaryCurrency',
      label: 'Primary Currency',
      value: selectedCustomer?.currency ? `${selectedCustomer.currency.code ?? selectedCustomer.currency.currencyId} - ${selectedCustomer.currency.name}` : '',
      displayValue: selectedCustomer?.currency ? `${selectedCustomer.currency.code ?? selectedCustomer.currency.currencyId} - ${selectedCustomer.currency.name}` : '-',
      helpText: 'Default transaction currency from the linked customer record.',
      fieldType: 'list',
      sourceText: 'Customers master data',
    },
    customerInactive: {
      key: 'customerInactive',
      label: 'Inactive',
      value: selectedCustomer ? (selectedCustomer.inactive ? 'Yes' : 'No') : '',
      displayValue: selectedCustomer ? (selectedCustomer.inactive ? 'Yes' : 'No') : '-',
      helpText: 'Indicates whether the linked customer is inactive for new activity.',
      fieldType: 'checkbox',
      sourceText: 'Customers master data',
    },
    id: {
      key: 'id',
      label: 'DB Id',
      value: '',
      displayValue: 'Auto-generated',
      helpText: 'Internal database identifier for this invoice record.',
      fieldType: 'text',
      subsectionTitle: 'Record Keys',
      subsectionDescription: 'Internal and foreign-key references for this invoice.',
    },
    customerId: {
      key: 'customerId',
      label: 'Customer',
      value: headerValues.customerId ?? '',
      displayValue: selectedCustomer
        ? `${selectedCustomer.customerId ?? 'CUSTOMER'} - ${selectedCustomer.name}`
        : '-',
      editable: true,
      type: 'select',
      options: customerOptions,
      helpText: 'Customer linked to this invoice.',
      fieldType: 'list',
      sourceText: 'Customers master data',
      subsectionTitle: 'Record Keys',
      subsectionDescription: 'Internal and foreign-key references for this invoice.',
    },
    salesOrderId: {
      key: 'salesOrderId',
      label: 'Sales Order',
      value: headerValues.salesOrderId ?? '',
      displayValue: selectedSalesOrder?.number ?? duplicateInvoice?.salesOrder?.number ?? '-',
      editable: true,
      type: 'select',
      options: salesOrderOptions,
      helpText: 'Optional source sales order that can seed this invoice.',
      fieldType: 'list',
      sourceText: 'Source transaction',
      subsectionTitle: 'Record Keys',
      subsectionDescription: 'Internal and foreign-key references for this invoice.',
    },
    userId: {
      key: 'userId',
      label: 'User Id',
      value: selectedSalesOrder?.user?.userId ?? '',
      displayValue: selectedSalesOrder?.user?.userId ?? '-',
      helpText: 'User identifier for the invoice creator/owner.',
      fieldType: 'text',
      sourceText: 'Users master data',
      subsectionTitle: 'Record Keys',
      subsectionDescription: 'Internal and foreign-key references for this invoice.',
    },
    number: {
      key: 'number',
      label: 'Invoice Id',
      value: '',
      displayValue: 'Auto-generated on save',
      helpText: 'Unique invoice number used across OTC workflows.',
      fieldType: 'text',
      subsectionTitle: 'Document Identity',
      subsectionDescription: 'Invoice numbering, source context, and ownership for this transaction.',
    },
    createdBy: {
      key: 'createdBy',
      label: 'Created By',
      value: createdByLabel,
      displayValue: createdByLabel,
      helpText: 'User who created the source sales order.',
      fieldType: 'text',
      sourceText: 'Users master data',
      subsectionTitle: 'Document Identity',
      subsectionDescription: 'Invoice numbering, source context, and ownership for this transaction.',
    },
    createdFrom: {
      key: 'createdFrom',
      label: 'Created From',
      value: selectedSalesOrder?.number ?? duplicateInvoice?.salesOrder?.number ?? '',
      displayValue: selectedSalesOrder?.number ?? duplicateInvoice?.salesOrder?.number ?? '-',
      helpText: 'Source sales order that will create this invoice.',
      fieldType: 'text',
      sourceText: 'Source transaction',
      subsectionTitle: 'Document Identity',
      subsectionDescription: 'Invoice numbering, source context, and ownership for this transaction.',
    },
    quoteId: {
      key: 'quoteId',
      label: 'Quote Id',
      value: selectedSalesOrder?.quote?.number ?? duplicateInvoice?.salesOrder?.quote?.number ?? '',
      displayValue: selectedSalesOrder?.quote?.number ?? duplicateInvoice?.salesOrder?.quote?.number ?? '-',
      helpText: 'Quote identifier linked through the sales order.',
      fieldType: 'text',
      sourceText: 'Source transaction',
      subsectionTitle: 'Document Identity',
      subsectionDescription: 'Invoice numbering, source context, and ownership for this transaction.',
    },
    opportunityId: {
      key: 'opportunityId',
      label: 'Opportunity Id',
      value: selectedSalesOrder?.quote?.opportunity?.opportunityNumber ?? duplicateInvoice?.salesOrder?.quote?.opportunity?.opportunityNumber ?? '',
      displayValue: selectedSalesOrder?.quote?.opportunity?.opportunityNumber ?? duplicateInvoice?.salesOrder?.quote?.opportunity?.opportunityNumber ?? '-',
      helpText: 'Opportunity identifier linked through the source quote.',
      fieldType: 'text',
      sourceText: 'Opportunities',
      subsectionTitle: 'Document Identity',
      subsectionDescription: 'Invoice numbering, source context, and ownership for this transaction.',
    },
    subsidiaryId: {
      key: 'subsidiaryId',
      label: 'Subsidiary',
      value: headerValues.subsidiaryId ?? '',
      displayValue:
        subsidiaries.find((subsidiary) => subsidiary.id === (headerValues.subsidiaryId ?? ''))
          ? `${subsidiaries.find((subsidiary) => subsidiary.id === (headerValues.subsidiaryId ?? ''))!.subsidiaryId} - ${subsidiaries.find((subsidiary) => subsidiary.id === (headerValues.subsidiaryId ?? ''))!.name}`
          : '-',
      editable: true,
      type: 'select',
      options: subsidiaryOptions,
      helpText: 'Subsidiary that will own the invoice.',
      fieldType: 'list',
      sourceText: 'Subsidiaries master data',
      subsectionTitle: 'Commercial Terms',
      subsectionDescription: 'Currency, status, and payment timing for this invoice.',
    },
    currencyId: {
      key: 'currencyId',
      label: 'Currency',
      value: headerValues.currencyId ?? '',
      displayValue:
        currencies.find((currency) => currency.id === (headerValues.currencyId ?? ''))
          ? `${currencies.find((currency) => currency.id === (headerValues.currencyId ?? ''))!.code ?? currencies.find((currency) => currency.id === (headerValues.currencyId ?? ''))!.currencyId} - ${currencies.find((currency) => currency.id === (headerValues.currencyId ?? ''))!.name}`
          : '-',
      editable: true,
      type: 'select',
      options: currencyOptions,
      helpText: 'Transaction currency for the invoice.',
      fieldType: 'list',
      sourceText: 'Currencies master data',
      subsectionTitle: 'Commercial Terms',
      subsectionDescription: 'Currency, status, and payment timing for this invoice.',
    },
    status: {
      key: 'status',
      label: 'Status',
      value: headerValues.status ?? 'draft',
      displayValue: headerValues.status ? headerValues.status.charAt(0).toUpperCase() + headerValues.status.slice(1) : 'Draft',
      editable: true,
      type: 'select',
      options: [
        { value: 'draft', label: 'Draft' },
        { value: 'sent', label: 'Sent' },
        { value: 'paid', label: 'Paid' },
        { value: 'void', label: 'Void' },
      ],
      helpText: 'Initial lifecycle stage of the invoice.',
      fieldType: 'list',
      subsectionTitle: 'Commercial Terms',
      subsectionDescription: 'Currency, status, and payment timing for this invoice.',
    },
    total: {
      key: 'total',
      label: 'Total',
      value: String(selectedSalesOrder?.total ?? duplicateInvoice?.total ?? 0),
      displayValue: fmtCurrency(selectedSalesOrder?.total ?? duplicateInvoice?.total ?? 0),
      helpText: 'Document total based on all copied sales order line amounts.',
      fieldType: 'currency',
      subsectionTitle: 'Commercial Terms',
      subsectionDescription: 'Currency, status, and payment timing for this invoice.',
    },
    dueDate: {
      key: 'dueDate',
      label: 'Due Date',
      value: headerValues.dueDate ?? '',
      displayValue: headerValues.dueDate ? fmtDocumentDate(headerValues.dueDate) : '-',
      editable: true,
      type: 'date',
      helpText: 'Date payment is due.',
      fieldType: 'date',
      subsectionTitle: 'Commercial Terms',
      subsectionDescription: 'Currency, status, and payment timing for this invoice.',
    },
    paidDate: {
      key: 'paidDate',
      label: 'Paid Date',
      value: headerValues.paidDate ?? '',
      displayValue: headerValues.paidDate ? fmtDocumentDate(headerValues.paidDate) : '-',
      editable: true,
      type: 'date',
      helpText: 'Date payment was completed.',
      fieldType: 'date',
      subsectionTitle: 'Commercial Terms',
      subsectionDescription: 'Currency, status, and payment timing for this invoice.',
    },
    createdAt: {
      key: 'createdAt',
      label: 'Created',
      value: '',
      displayValue: fmtDocumentDate(new Date()),
      helpText: 'Date/time the invoice record is created.',
      fieldType: 'date',
      subsectionTitle: 'System Dates',
      subsectionDescription: 'System-managed lifecycle timestamps.',
    },
    updatedAt: {
      key: 'updatedAt',
      label: 'Last Modified',
      value: '',
      displayValue: 'On save',
      helpText: 'Date/time the invoice record was last modified.',
      fieldType: 'date',
      subsectionTitle: 'System Dates',
      subsectionDescription: 'System-managed lifecycle timestamps.',
    },
  }

  const headerSections: PurchaseOrderHeaderSection[] = buildConfiguredTransactionSections({
    fields: INVOICE_DETAIL_FIELDS,
    layout: customization,
    fieldDefinitions: headerFieldDefinitions,
    sectionDescriptions,
  })

  async function handleCreate(values: Record<string, string>) {
    setSaving(true)
    setError('')

    const salesOrderId = values.salesOrderId?.trim()
    const customerId = values.customerId?.trim()
    if (!salesOrderId && !customerId) {
      setSaving(false)
      setError('Customer is required')
      return { ok: false, error: 'Customer is required' }
    }

    try {
      const response = await fetch('/api/invoices', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          duplicateFrom: duplicateFrom || null,
          salesOrderId: salesOrderId || null,
          customerId: customerId || null,
          subsidiaryId: values.subsidiaryId?.trim() || null,
          currencyId: values.currencyId?.trim() || null,
          status: values.status?.trim() || 'draft',
          dueDate: values.dueDate?.trim() || null,
          paidDate: values.paidDate?.trim() || null,
        }),
      })

      const body = await response.json()
      if (!response.ok) {
        const nextError = body?.error || 'Unable to create invoice'
        setError(nextError)
        return { ok: false, error: nextError }
      }

      router.push(`/invoices/${body.id}`)
      return { ok: true }
    } catch {
      const nextError = 'Unable to create invoice'
      setError(nextError)
      return { ok: false, error: nextError }
    } finally {
      setSaving(false)
    }
  }

  const lineRows = (selectedSalesOrder?.lineItems ?? duplicateInvoice?.lineItems ?? []).map((line, index) => ({
    id: line.id,
    displayOrder: index,
    itemRecordId: line.item?.id ?? null,
    itemId: line.item?.itemId ?? null,
    itemName: line.item?.name ?? null,
    description: line.description,
    quantity: line.quantity,
    receivedQuantity: 0,
    billedQuantity: 0,
    openQuantity: line.quantity,
    unitPrice: line.unitPrice,
    lineTotal: line.lineTotal,
  }))

  return (
    <RecordDetailPageShell
      backHref="/invoices"
      backLabel="<- Back to Invoices"
      meta={duplicateFrom ? 'Duplicate' : 'New'}
      title={selectedCustomer?.name ?? (duplicateFrom ? 'Duplicate Invoice' : 'New Invoice')}
      badge={
        <div className="flex flex-wrap gap-2">
          <span
            className="inline-block rounded-full px-3 py-0.5 text-sm"
            style={{ backgroundColor: 'rgba(59,130,246,0.18)', color: 'var(--accent-primary-strong)' }}
          >
            Invoice
          </span>
          <span
            className="inline-block rounded-full px-3 py-0.5 text-sm font-medium"
            style={{ backgroundColor: 'rgba(255,255,255,0.07)', color: 'var(--text-muted)' }}
          >
            Draft
          </span>
        </div>
      }
      widthClassName="w-full max-w-none"
      actions={
        <>
          <button
            type="button"
            onClick={() => router.push('/invoices')}
            className="rounded-md border px-3 py-1.5 text-xs font-medium"
            style={{ borderColor: 'var(--border-muted)', color: 'var(--text-secondary)' }}
          >
            Cancel
          </button>
          <button
            type="submit"
            form="new-invoice-form"
            disabled={saving || (!duplicateFrom && !selectedSalesOrder && !selectedCustomer)}
            className="rounded-md px-3 py-1.5 text-xs font-semibold text-white disabled:opacity-60"
            style={{ backgroundColor: 'var(--accent-primary-strong)' }}
          >
            {saving ? 'Saving...' : duplicateFrom ? 'Duplicate' : 'Save'}
          </button>
        </>
      }
    >
      <PurchaseOrderHeaderSections
        editing
        sections={headerSections}
        columns={customization.formColumns}
        formId="new-invoice-form"
        submitMode="controlled"
        onSubmit={handleCreate}
        onValuesChange={(nextValues) => {
          setHeaderValues((previousValues) => {
            const salesOrderChanged = nextValues.salesOrderId !== previousValues.salesOrderId
            const customerChanged = nextValues.customerId !== previousValues.customerId

            if (salesOrderChanged) {
              const nextSalesOrder = salesOrders.find((salesOrder) => salesOrder.id === nextValues.salesOrderId)
              if (nextSalesOrder) {
                return {
                  ...nextValues,
                  customerId: nextSalesOrder.customer.id,
                  subsidiaryId: nextValues.subsidiaryId || nextSalesOrder.subsidiary?.id || nextSalesOrder.customer.subsidiary?.id || '',
                  currencyId: nextValues.currencyId || nextSalesOrder.currency?.id || nextSalesOrder.customer.currency?.id || '',
                }
              }
            }

            if (customerChanged && !nextValues.salesOrderId) {
              const nextCustomer = customers.find((customer) => customer.id === nextValues.customerId)
              if (nextCustomer) {
                return {
                  ...nextValues,
                  subsidiaryId: nextValues.subsidiaryId || nextCustomer.subsidiary?.id || '',
                  currencyId: nextValues.currencyId || nextCustomer.currency?.id || '',
                }
              }
            }

            return nextValues
          })
        }}
      />

      <div className="mt-6">
        {lineRows.length > 0 ? (
          <PurchaseOrderLineItemsSection
            rows={lineRows}
            editing={false}
            purchaseOrderId="draft-invoice"
            userId=""
            itemOptions={lineRows
              .filter((line) => line.itemRecordId && line.itemName)
              .map((line) => ({
                id: line.itemRecordId!,
                itemId: line.itemId ?? 'ITEM',
                name: line.itemName ?? 'Item',
                unitPrice: line.unitPrice,
              }))}
            draftMode
            sectionTitle="Invoice Line Items"
          />
        ) : (
          <RecordDetailSection title="Invoice Line Items" count={0}>
            <RecordDetailEmptyState message="Select a sales order to preview the invoice line items that will be copied on save." />
          </RecordDetailSection>
        )}
      </div>

      {error ? (
        <p className="text-sm" style={{ color: 'var(--danger)' }}>
          {error}
        </p>
      ) : null}
    </RecordDetailPageShell>
  )
}
