// Generated by sync-transaction-framework

import { NextRequest, NextResponse } from 'next/server'
import {
  defaultInvoiceReceiptDetailCustomization,
  INVOICE_RECEIPT_DETAIL_FIELDS,
  type InvoiceReceiptDetailCustomizationConfig,
} from '@/lib/invoice-receipt-detail-customization'
import {
  loadInvoiceReceiptDetailCustomization,
  saveInvoiceReceiptDetailCustomization,
} from '@/lib/invoice-receipt-detail-customization-store'

export async function GET() {
  try {
    const config = await loadInvoiceReceiptDetailCustomization()
    return NextResponse.json({ config, fields: INVOICE_RECEIPT_DETAIL_FIELDS })
  } catch {
    return NextResponse.json({ error: 'Failed to load invoice-receipts detail customization' }, { status: 500 })
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const nextConfig = ((body as { config?: unknown }).config ?? defaultInvoiceReceiptDetailCustomization()) as InvoiceReceiptDetailCustomizationConfig
    const saved = await saveInvoiceReceiptDetailCustomization(nextConfig)
    return NextResponse.json({ config: saved, fields: INVOICE_RECEIPT_DETAIL_FIELDS })
  } catch {
    return NextResponse.json({ error: 'Failed to save invoice-receipts detail customization' }, { status: 500 })
  }
}
